### ISSUE TITLE
Multiple browser configurations lead to filename error

### ISSUE THREAD

**Issue by d060270** [SAP/ui5-uiveri5#115]
Hello,

I observed the following issue when starting UIveri5 with a configuration that contains multiple browser objects and capabilities:

```javascript
browsers: [
    {
        browserName: "chrome",
        capabilities: {
            platform: "LINUX",
            platformName: "LINUX",
            chromeOptions: {
                w3c: false,
                args: [
                    "disable-popup-blocking",
                    "--no-sandbox",
                    "--disable-dev-shm-usage"
                ]
            },
            remoteWebDriverOptions: {
                platformName: "linux",
                maximized: false,
                viewportSize: {
                    width: 1024,
                    height: 768
                }
            }
        }
    },
    {
        browserName: "chrome",
        capabilities: {
            platform: "ANDROID",
            deviceName: "samsung_galaxy_s6_9.0",
            remoteWebDriverOptions: {
                maximized: false
            }
        }
    }
]
```

With the above configuration, a runtime error is thrown:
```
Error: Error while processing: /home/user/workspace/UIVeri5Test/node_modules/@ui5/uiveri5/selenium//home/user/workspace/UIVeri5Test/node_modules/@ui5/uiveri5/selenium/chromedriver-76.0.3809.126.zip ,details: Invalid filename
    at WriteStream.<anonymous> (/home/user/workspace/UIVeri5Test/node_modules/@ui5/uiveri5/src/connection/directConnectionProvider.js:275:22)
    at WriteStream.emit (events.js:189:13)
    at finishMaybe (_stream_writable.js:641:14)
    at stream._final (_stream_writable.js:619:5)
    at WriteStream._final (internal/fs/streams.js:263:3)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I was able to trace it back to `@ui5/uiveri5/src/connection/directConnectionProvider.js:302`
```javascript
DirectConnectionProvider.prototype._downloadBinary = function (binary) {
  var that = this;
  var root = that._getSeleniumRoot();

  if(typeof binary.executable === 'object') {
    binary.executable =  root + '/' + binary.executable[that.config.osTypeString];
  } else {
    binary.executable =  root + '/' + binary.executable;
  }

  return that._getLatestVersion(binary).then(function () {
    return that._checkIfBinaryExists(binary.executable, true).then(function () {
      return that._downloadDriver(binary);
    });
  });
};
```

Where the `binary.executable` is overwritten with the root and the executable path again when the second browser is processed.
This causes it to be appended to the path again which, of course, is invalid, so the chromedriver.zip file cannot be unpacked.

**Comment by maximnaidenov** [comment]
Hi,
thanks for reporting and debugging but multiple browser configurations are not supported. There are further problems down the road. Please use CI/CD configurations for parallelization of test executions.
