### ISSUE TITLE
Not able to launch Safari browser, getting error "SessionNotCreatedError: Request body does not contain required parameter 'capabilities'."

### ISSUE THREAD

**Issue by mkrish03** [SAP/ui5-uiveri5#116]
I am trying to run my script in Safari 13.0.1 version using uiveri5, I am getting SessionNotCreatedError: Request body does not contain required parameter 'capabilities' when executing the scripts.

capabilities in conf.js
browsers: [{
        browserName: 'safari',
        capabilities: {
          safariOptions: {
            setTechnologyPreview: true,
            addArguments:['--legacy']
          }
        }
      }]

console:
uiveri5 --config.browsers[0].browserName=safari --config.browsers[0].capabilities.safariOptions.setTechnologyPreview=true --config.browsers[0].capabilities.safariOptions.addArguments[0]=--legacy
INFO: @ui5/uiveri5 v1.40.0
INFO: Resolving specs
INFO: Executing 1 specs
(node:34864) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[20:27:46] I/launcher - Running 1 instances of WebDriver
[20:27:47] E/launcher - Request body does not contain required parameter 'capabilities'.
[20:27:47] E/launcher - SessionNotCreatedError: Request body does not contain required parameter 'capabilities'.
    at Object.throwDecodedError (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at createDriver (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/index.js:635:14)
    at DirectDriverProvider.getNewDriver (/usr/local/lib/node_modules/@ui5/uiveri5/src/connection/directConnectionProvider.js:616:12)
    at Runner.createBrowser (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:834:54)
    at /usr/local/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:604:44
[20:27:47] E/launcher - Process exited with error code 199

**Comment by moinuddin14** [comment]
I am also facing the same issue. Unable to launch safari browser.

**Comment by ahusemann** [comment]
Same issue here: macOS 10.14.6, Safari 13.0.1, uiveri5 v1.41.0

**Comment by maximnaidenov** [comment]
Hi, I did some investigation and it seems the problem is somehow bigger, this is the synopsis:
https://github.com/SeleniumHQ/selenium/issues/6431#issuecomment-477408650
Unfortunatelly it won't be so easy to switch to selenium 4 as they removed the control flow and this would mean a total rewrite of the tests to use async/await and this causes a totally new set of problems altogether. 
Please give me some time to research what is the difference between webdriver an w3c protocol and if we can somehow overcome it.

**Comment by harshaltikkas** [comment]
dfdf
