### ISSUE TITLE
Binding Context Matcher not working

### ISSUE THREAD

**Issue by sebbi08** [SAP/ui5-uiveri5#117]
Hi i currently stugling getting the uiveri5 bindingPath selector to work i have the following control binding.

![image](https://user-images.githubusercontent.com/9070136/66030868-97252500-e502-11e9-91eb-fa60005da9ed.png)

and the following selector:
```js
bindingPath: {
               model: “dashboardData”,
               path: “/MarketEventSet(1)“,
               propertyPath: “Text”
           }
```
what am i missing ??

**Comment by tsaleksandrova** [comment]
Hi Sebastian,
The model property is called "modelName". If this doesn't help, please attach a detailed error log (run tests with "--v" parameter)

**Comment by sebbi08** [comment]
i have again tried it with the following control

![image](https://user-images.githubusercontent.com/9070136/66047893-e1210180-e528-11e9-9466-3b21fac6529e.png)

and the selector :

```js
bindingPath: {
                modelName: "moreView",
                path: "/navTargets/2",
                propertyPath: "visible"
            }
```

and it was not working.

is it because i am using ui5 1.52.12.

[here](https://github.com/SAP/ui5-uiveri5/blob/master/docs/usage/locators.md) it says it sould be compatible but when looking at the BindingPath matcher 1.52 - 1.60.
https://openui5.hana.ondemand.com/1.52.12/#/api/sap.ui.test.matchers.BindingPath/constructor
https://openui5.hana.ondemand.com/1.60.4/#/api/sap.ui.test.matchers.BindingPath/constructor

till 1.60 the binding path mathcer dose not have the `propertyPath` Property


here is the verbose output


```
INFO: @ui5/uiveri5 v1.40.0
DEBUG: Config from command-line: {"seleniumLoopback":false,"ignoreNothing":true,"params":{"user":***********,"pwd":"***********"},"v":1,"verbose":1,"conf":"/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/conf.js"}
DEBUG: Loading default config from: /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/conf.js
DEBUG: Loading profile config config from: ../conf/integration.profile.conf.js
DEBUG: Loading common profile config from: ../conf/profile.conf.js
DEBUG: Resolved runtime: {"browserName":"chrome","platformName":"mac","platformResolution":"1280x1024","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}
DEBUG: Config after resolving config file and profile: {"timeouts":{"waitForUI5Delta":200,"getPageTimeout":10000,"allScriptsTimeout":11000,"defaultTimeoutInterval":30000,"waitForUI5PollingInterval":400},"useClassicalWaitForUI5":false,"connection":"direct","connectionConfigs":{"direct":{"name":"./connection/directConnectionProvider","binaries":{"selenium":{"version":"3.12","patch":"0","filename":"selenium-server-standalone","url":"https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar","executable":"selenium-server-standalone-3.12.0.jar"},"chromedriver":{"version":"{chrome.latest}","unzip":true,"filename":"chromedriver","baseurl":"https://chromedriver.storage.googleapis.com","url":"https://chromedriver.storage.googleapis.com/{chrome.latest}/chromedriver_mac64.zip","latestVersionUrl":"https://chromedriver.storage.googleapis.com/LATEST_RELEASE_{chrome.latest}","latestVersionFileUrl":"https://raw.githubusercontent.com/SAP/ui5-uiveri5/master/driverVersions.json","executable":{"win32":"chromedriver-{chrome.latest}.exe","mac64":"chromedriver-{chrome.latest}","linux32":"chromedriver-{chrome.latest}","linux64":"chromedriver-{chrome.latest}"}},"iedriver":{"version":"3.12","patch":"0","unzip":true,"filename":"IEDriverServer.exe","url":"http://selenium-release.storage.googleapis.com/3.12/IEDriverServer_Win32_3.12.0.zip","executable":"IEDriverServer.exe"},"geckodriver":{"version":"{latest}","unzip":"false","untar":"true","filename":"geckodriver","baseurl":"http://github.com/mozilla/geckodriver/releases","url":"http://github.com/mozilla/geckodriver/releases/download/{latest}/geckodriver-{latest}-macos.tar.gz","latestVersionUrlRedirect":"http://github.com/mozilla/geckodriver/releases/latest","executable":{"win32":"geckodriver-{latest}.exe","win64":"geckodriver-{latest}.exe","mac64":"geckodriver-{latest}","linux32":"geckodriver-{latest}","linux64":"geckodriver-{latest}"}}}}},"browserCapabilities":{"browser,chrome":{"android":{"*":{"deviceName":"android"}}},"firefox,ie,edge,safari,chrome,chromium":{"windows,mac,linux":{"*":{"remoteWebDriverOptions":{"maximized":true}}}},"chrome,chromium":{"*":{"*":{"chromeOptions":{"args":["disable-infobars"]}}}},"safari":{"mac":{"*":{"safaridriverOptions":{"addArguments":["--legacy"]}}}},"chromeMobileEmulation":{"*":{"*":{"browserName":"chrome","remoteWebDriverOptions":{"maximized":false,"scaling":{"x":4,"y":4}},"chromeOptions":{"mobileEmulation":{"deviceMetrics":{"width":360,"height":560,"pixelRatio":4}}}}}},"chromeHeadless":{"*":{"*":{"browserName":"chrome","chromeOptions":{"args":["--headless","--no-sandbox"]}}}}},"auth":{"basic":{"name":"./authenticator/basicUrlAuthenticator","user":"***********","pass":"***********"}},"authConfigs":{"plain":{"name":"./authenticator/plainAuthenticator"},"basic":{"name":"./authenticator/basicUrlAuthenticator"},"fiori-form":{"name":"./authenticator/formAuthenticator","userFieldSelector":"#USERNAME_BLOCK input","passFieldSelector":"#PASSWORD_BLOCK input","logonButtonSelector":"#LOGIN_LINK"},"sapcloud-form":{"name":"./authenticator/formAuthenticator","userFieldSelector":"#j_username","passFieldSelector":"#j_password","logonButtonSelector":"#logOnFormSubmit"}},"reporters":[{"name":"./reporter/consoleReporter"},{"name":"./reporter/screenshotReporter"}],"locators":[{"name":"./defaultLocators"}],"plugins":[],"matchers":[],"specResolver":"./resolver/localSpecResolver","pageLoading":{"wait":"3000"},"takeScreenshot":{"onExpectFailure":true,"onExpectSuccess":true,"onAction":true},"profile":"integration","debug":true,"verbose":1,"specs":"webapp/test/e2e/**/*.spec.js","baseUrl":"http://localhost:60423/test/indexLocal.html?sap-ui-debug=true&sov-mock=false#/more","browsers":[{"browserName":"chrome","platformName":"mac","platformResolution":"1280x1024","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}],"seleniumLoopback":false,"ignoreNothing":true,"params":{"user":***********,"pwd":"***********"},"v":1,"conf":"/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/conf.js","osTypeString":"mac64","runtimes":[{"browserName":"chrome","platformName":"mac","platformResolution":"1280x1024","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}]}
DEBUG: Current working directory: /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka
DEBUG: Loading module: ./resolver/localSpecResolver with instance config: {}
INFO: Resolving specs
DEBUG: Resolving specs from: webapp/test/e2e/**/*.spec.js
DEBUG: Spec found, name: test ,path: /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/webapp/test/e2e/test.spec.js ,url:http://localhost:60423/test/indexLocal.html?sap-ui-debug=true&sov-mock=false#/more
DEBUG: Loading module: ./connection/directConnectionProvider with instance config: {"binaries":{"selenium":{"version":"3.12","patch":"0","filename":"selenium-server-standalone","url":"https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar","executable":"selenium-server-standalone-3.12.0.jar"},"chromedriver":{"version":"{chrome.latest}","unzip":true,"filename":"chromedriver","baseurl":"https://chromedriver.storage.googleapis.com","url":"https://chromedriver.storage.googleapis.com/{chrome.latest}/chromedriver_mac64.zip","latestVersionUrl":"https://chromedriver.storage.googleapis.com/LATEST_RELEASE_{chrome.latest}","latestVersionFileUrl":"https://raw.githubusercontent.com/SAP/ui5-uiveri5/master/driverVersions.json","executable":{"win32":"chromedriver-{chrome.latest}.exe","mac64":"chromedriver-{chrome.latest}","linux32":"chromedriver-{chrome.latest}","linux64":"chromedriver-{chrome.latest}"}},"iedriver":{"version":"3.12","patch":"0","unzip":true,"filename":"IEDriverServer.exe","url":"http://selenium-release.storage.googleapis.com/3.12/IEDriverServer_Win32_3.12.0.zip","executable":"IEDriverServer.exe"},"geckodriver":{"version":"{latest}","unzip":"false","untar":"true","filename":"geckodriver","baseurl":"http://github.com/mozilla/geckodriver/releases","url":"http://github.com/mozilla/geckodriver/releases/download/{latest}/geckodriver-{latest}-macos.tar.gz","latestVersionUrlRedirect":"http://github.com/mozilla/geckodriver/releases/latest","executable":{"win32":"geckodriver-{latest}.exe","win64":"geckodriver-{latest}.exe","mac64":"geckodriver-{latest}","linux32":"geckodriver-{latest}","linux64":"geckodriver-{latest}"}}}}
DEBUG: Setting getPageTimeout: 10000
DEBUG: Setting allScriptsTimeout: 11000
DEBUG: Setting defaultTimeoutInterval: 30000
DEBUG: Resolved protractor multiCapabilities from runtime: [{"browserName":"chrome","platform":"MAC","chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true},"runtime":{"browserName":"chrome","platformName":"mac","platformResolution":"1280x1024","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}}]
DEBUG: Loading BDD-style page object factory
DEBUG: Setting up connection provider environment
INFO: Check for latest major version of: chromedriver
INFO: Found latest major version of chromedriver: 76
INFO: Check for latest version of: chromedriver
INFO: Found latest version of chromedriver: 76.0.3809.126
INFO: Found correct binary locally: /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/@ui5/uiveri5/selenium/chromedriver-76.0.3809.126
INFO: Downloading webdriver binary: https://chromedriver.storage.googleapis.com/76.0.3809.126/chromedriver_mac64.zip
INFO: Executing 1 specs
[15:35:51] D/launcher - Running with --troubleshoot
[15:35:51] D/launcher - Protractor version: 5.3.2
[15:35:51] D/launcher - Your base url for tests is http://localhost:60423/test/indexLocal.html?sap-ui-debug=true&sov-mock=false#/more
[15:35:51] D/plugins - Plugin "Plugin #0" loaded.
[15:35:51] I/launcher - Running 1 instances of WebDriver
DEBUG: Starting local chromedriver with executable: /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/@ui5/uiveri5/selenium/chromedriver-76.0.3809.126
[15:35:52] D/runner - WebDriver session successfully started with capabilities Capabilities {
  map_: Map {
    'acceptInsecureCerts' => false,
    'acceptSslCerts' => false,
    'applicationCacheEnabled' => false,
    'browserConnectionEnabled' => false,
    'browserName' => 'chrome',
    'chrome' => {
      chromedriverVersion: '76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024})',
      userDataDir: '/var/folders/7y/z_ptxkpd6n7_9t448hfpwbl0zvx_vb/T/.com.google.Chrome.hAwze0'
    },
    'cssSelectorsEnabled' => true,
    'databaseEnabled' => false,
    'goog:chromeOptions' => { debuggerAddress: 'localhost:53705' },
    'handlesAlerts' => true,
    'hasTouchScreen' => false,
    'javascriptEnabled' => true,
    'locationContextEnabled' => true,
    'mobileEmulationEnabled' => false,
    'nativeEvents' => true,
    'networkConnectionEnabled' => false,
    'pageLoadStrategy' => 'normal',
    'platform' => 'Mac OS X',
    'proxy' => {},
    'rotatable' => false,
    'setWindowRect' => true,
    'strictFileInteractability' => false,
    'takesHeapSnapshot' => true,
    'takesScreenshot' => true,
    'timeouts' => { implicit: 0, pageLoad: 300000, script: 30000 },
    'unexpectedAlertBehaviour' => 'ignore',
    'version' => '77.0.3865.90',
    'webStorageEnabled' => true
  }
}
[15:35:52] D/runner - Running with spec files /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/webapp/test/e2e/test.spec.js
DEBUG: Loading module: ./defaultLocators with instance config: {}
DEBUG: Registering default locators
DEBUG: Loading module: ./reporter/consoleReporter with instance config: {}
DEBUG: Loading module: ./reporter/screenshotReporter with instance config: {}
INFO: Suite started: test
INFO: Spec started: Test 0
DEBUG: Runtime resolved from capabilities: {"browserName":"chrome","platformName":"mac","platformResolution":"1280x1024","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true}}}
DEBUG: Maximizing browser window
DEBUG: Loading module: ./authenticator/basicUrlAuthenticator with instance config: {"name":"./authenticator/basicUrlAuthenticator","user":"***********","pass":"***********"}
DEBUG: Execute async script: loadUI5Dependencies with params: {"waitForUI5Timeout":10800,"waitForUI5PollingInterval":400,"useClassicalWaitForUI5":false}
INFO: Opening: http://localhost:60423/test/indexLocal.html?sap-ui-debug=true&sov-mock=false#/more
DEBUG: Initial page load wait: 3000ms
DEBUG: Async script: loadUI5Dependencies logs:
Loading waitForUI5 implementation
Loading OPA5 control locator utilities.
Loading OPA5 waitForUI5 implementation.
DEBUG: Async script: loadUI5Dependencies result: undefined
INFO: UI5 Version: 0.18.0
INFO: UI5 Timestamp: 201910021535
DEBUG: No elements found using by.control locator. This is what control locator last logged:
DEBUG: Screenshot created "target/report/screenshots/test-Test-0_0_fail_2019-10-02T13-35-59.png"
INFO: Expectation FAILED: Failed: No element found using locator: by.control({"controlType":"sov.lib.shape.SidebarItem","bindingPath":{"modelName":"moreView","path":"/navTargets/2","propertyPath":"visible"}})
DEBUG: Expectation FAILED stack: NoSuchElementError: No element found using locator: by.control({"controlType":"sov.lib.shape.SidebarItem","bindingPath":{"modelName":"moreView","path":"/navTargets/2","propertyPath":"visible"}})
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/built/element.js:814:27
    at ManagedPromise.invokeCallback_ (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:2927:27
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:668:7
    at processTicksAndRejections (internal/process/task_queues.js:85:5)Error
    at ElementArrayFinder.applyAction_ (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/built/element.js:459:27)
    at ElementArrayFinder.<computed> [as click] (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/built/element.js:91:29)
    at ElementFinder.<computed> [as click] (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/built/element.js:831:22)
    at UserContext.<anonymous> (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/webapp/test/e2e/test.spec.js:20:13)
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasminewd2/index.js:112:25
    at new ManagedPromise (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:1077:7)
    at ControlFlow.promise (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:2505:12)
    at schedulerExecute (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasminewd2/index.js:95:18)
    at TaskQueue.execute_ (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:2974:25
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:668:7
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
From: Task: Run it("Test 0") in control flow
    at UserContext.<anonymous> (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasminewd2/index.js:94:19)
    at attempt (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
    at QueueRunner.run (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
    at runNext (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4257:20)
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4264:13
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4172:9
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasminewd2/index.js:64:48
    at ControlFlow.emit (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/events.js:62:21)
    at ControlFlow.shutdown_ (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:2674:10)
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:2599:53
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:2728:9
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/selenium-webdriver/lib/promise.js:668:7
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
From asynchronous test:
Error
    at Suite.<anonymous> (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/webapp/test/e2e/test.spec.js:3:5)
    at addSpecsToSuite (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1107:25)
    at Env.describe (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1074:7)
    at describe (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4399:18)
    at Object.<anonymous> (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/webapp/test/e2e/test.spec.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasmine/lib/jasmine.js:93:5
    at Array.forEach (<anonymous>)
    at Jasmine.loadSpecs (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasmine/lib/jasmine.js:92:18)
    at Jasmine.execute (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/jasmine/lib/jasmine.js:197:8)
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/built/frameworks/jasmine.js:132:15
    at Function.promise (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/node_modules/q/q.js:682:9)
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/built/frameworks/jasmine.js:104:14
    at _fulfilled (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/node_modules/q/q.js:834:54)
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/Users/sebastian.mahr/Code/Sovanta/Edeka/comp-planning-edeka/node_modules/protractor/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
INFO: Spec finished: Test 0 with status: FAILED
INFO: Suite finished: test with status: FAILED for: 6.882s
INFO: Suite specs summary, total: 1, passed: 0, failed: 1, pending: 0, disabled: 0
INFO: Suite expectations summary, total: 1, passed: 0, failed total: 1, failed with error: 1, failed with image comparison: 0
INFO: Overall status: FAILED for: 6.884s
INFO: Overall suites summary, total: 1, passed: 0, failed: 1
INFO: Overall specs summary, total: 1, passed: 0, failed: 1, pending: 0, disabled: 0
INFO: Overall expectations summary, total: 1, passed: 0, failed total: 1, failed with error: 1, failed with image comparison: 0
[15:35:59] I/launcher - 0 instance(s) of WebDriver still running
[15:35:59] I/launcher - chrome #01 failed 1 test(s)
[15:35:59] I/launcher - overall: 1 failed spec(s)
DEBUG: Tearing down connection provider environment
[15:35:59] E/launcher - Process exited with error code 1

```

**Comment by sebbi08** [comment]
ok i am a blody fool :/ i had an second selector for the `controlType`and this was not correct now it is working
