### ISSUE TITLE
How to disable the default HTML Screenshot Reporter

### ISSUE THREAD

**Issue by ot94** [SAP/ui5-uiveri5#123]
Hello,
I'm trying to disable the HTML Screenshot reporter that is set on default. 
I have added the reporters property in my config file and have specified only the jUnit Reporter there as follows:
```
reporters: [{
        name: "./reporter/junitReporter"
}],
```
 yet I still get a HTML report after every test as well.

Regards,
Philip

**Comment by maximnaidenov** [comment]
Hi,
it seems we never considered the scenario of removing a default reporter. We will check for a solution but till then you can use the following workarounds:
1. Disable all screenshots within takeScreenshot: {} config. This won't prevent the report.html generation but at least will not generate the screenshots
2. Remove the "profile: integration" clause from your conf. and instead copy the content of integration.profile.js:  https://github.com/SAP/ui5-uiveri5/blob/master/conf/integration.profile.conf.js
and just remove the reporters array definition

**Comment by tsaleksandrova** [comment]
in fact, I think the user should be able to disable Or configure a reporter, and the configuration with highest priority should be applied (e.g. console args -> user conf.js -> profile) -- right now if I specify the same reporter with different instance config, I will get duplicate reports (or 1 with merged data from both, depending on the config)

**Comment by maximnaidenov** [comment]
Configuring is cumbersome but possible - just reference the reporter with index e.g. reporters[0]. But removing is not possible IMHO. Technically this is the same problem - how to "request" another action that is not merging, which is the "default" to be applied on duplicated array definition.

**Comment by ot94** [comment]
> 1. Disable all screenshots within takeScreenshot: {} config. This won't prevent the report.html generation but at least will not generate the screenshots
> 2. Remove the "profile: integration" clause from your conf. and instead copy the content of integration.profile.js:  https://github.com/SAP/ui5-uiveri5/blob/master/conf/integration.profile.conf.js
>    and just remove the reporters array definition

Hello,
this workaround somehow breaks my test at the second spec, maybe I didn't implement it correctly. I replaced the HTML Screenshot reporter with the JUnit Reporter. Here is my conf.js (with censored baseUrl):
```
exports.config = {
  specResolver: './resolver/localSpecResolver',
  pageLoading: {
    /* used to overcome issues due to pending async  work that was started before the waitForUI5 was injected */
    wait: '3000'
  },
  takeScreenshot: {
    onExpectFailure: false,
    onExpectSuccess: false,
    onAction: false
  },
  reporters: {
    name: "./reporter/junitReporter"
  },
  baseUrl: CENSORED,
  browsers: [{
    browserName: "chrome",
    capabilities: {
      remoteWebDriverOptions: {
        maximized: false
      }
    }
  }],
  connectionConfigs: {
    direct: {
      binaries: {
        chromedriver: {
          localPath: 'C:\\Users\\pt\\AppData\\Roaming\\npm\\node_modules\\@ui5\\uiveri5\\selenium\\chromedriver-76.0.3809.126.exe'
        }
      }
    }
  }
}
```
and here is an excerpt from the verbose logging:
```
DEBUG: Loading module: ./defaultLocators with instance config: {}
DEBUG: Registering default locators
DEBUG: Loading module: ./reporter/consoleReporter with instance config: {}
DEBUG: Loading module: ./reporter/junitReporter with instance config: {}
INFO: Suite started: SFCStartTest
INFO: Spec started: should open the Value Help Dialog
DEBUG: Runtime resolved from capabilities: {"browserName":"chrome","capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":false}},"platformName":"windows","platformResolution":"1600x1200","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"}}
DEBUG: Loading module: ./authenticator/plainAuthenticator with instance config: {}
DEBUG: Execute async script: loadUI5Dependencies with params: {"waitForUI5Timeout":10800,"waitForUI5PollingInterval":400,"useClassicalWaitForUI5":false}
INFO: Opening: CENSORED
DEBUG: Waiting for redirect to complete, current url: CENSORED
DEBUG: Initial page load wait: 3000ms
DEBUG: Async script: loadUI5Dependencies logs:
Loading waitForUI5 implementation
Loading OPA5 control locator utilities.
Loading OPA5 waitForUI5 implementation.
DEBUG: Async script: loadUI5Dependencies result: undefined
INFO: UI5 Version: 1.52.33
INFO: UI5 Timestamp: 201906121429
INFO: Spec finished: should open the Value Help Dialog with status: PASSED
INFO: Spec started: should load all available shop orders
INFO: Expectation FAILED: Failed: element not interactable
  (Session info: chrome=77.0.3865.120)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Windows NT 10.0.17763 x86_64)
DEBUG: Expectation FAILED stack: ElementNotVisibleError: element not interactable
  (Session info: chrome=77.0.3865.120)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Windows NT 10.0.17763 x86_64)
    at Object.checkLegacyResponse (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebElement.click()
    at Driver.schedule (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at WebElement.schedule_ (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
    at WebElement.click (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\webdriver.js:2092:17)
    at actionFn (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:89:44)
    at Array.map (<anonymous>)
    at C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:461:65
    at ManagedPromise.invokeCallback_ (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2927:27Error
    at ElementArrayFinder.applyAction_ (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.<computed> [as click] (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:91:29)
    at Object.selectAllSO (C:\workspaces\uiveri5-workspace\SFCSearchTest\pageObjects.js:91:37)
    at UserContext.<anonymous> (C:\workspaces\uiveri5-workspace\SFCStartTest.spec.js:10:24)
    at C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("should load all available shop orders") in control flow
    at UserContext.<anonymous> (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
    at C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
    at C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
    at C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:64:48
    at ControlFlow.emit (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\events.js:62:21)
    at ControlFlow.shutdown_ (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2674:10)
    at C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2599:53
From asynchronous test:
Error
    at Suite.<anonymous> (C:\workspaces\uiveri5-workspace\SFCStartTest.spec.js:9:5)
    at addSpecsToSuite (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\pt\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (C:\workspaces\uiveri5-workspace\SFCStartTest.spec.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
INFO: Spec finished: should load all available shop orders with status: FAILED
```

**Comment by maximnaidenov** [comment]
I don't think the failure is due to the changes in config, it looks like application issue. Can you check the screenshot report and see what is the problem there ?. Otherwise, the config looks fine.
We will address the underlying issue with removing any of the default modules, will updatr you here when ready.

**Comment by vobu** [comment]
hi, any updates on disabling screenshots completely via a config option?
sounds like a small change only 
\*duck\* (I'll show myself out :) )

**Comment by tsaleksandrova** [comment]
update to 1.42, and in your config file add
```
reporters: {
  disabled: [
    {name: './reporter/screenshotReporter'}
  ]
}
```

**Comment by vobu** [comment]
w00t, works 🤙 🕺
