### ISSUE TITLE
uiveri5 errors with JRE 11

### ISSUE THREAD

**Issue by vobu** [SAP/ui5-uiveri5#16]
Hi, using JRE 11, the `uiveri5` binary fails to run. It works finde with JRE 8. Independent of the `node` version in use (tried it w/ v8 + v11).
~~~bash
Naunet: ~/git/test-proj/src/specs > uiveri5 
INFO: @ui5/uiveri5 v1.35.5
INFO: Resolving specs
INFO: Check for latest version of: chromedriver
(node:33709) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
INFO: Found correct webdriver locally: /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/selenium/selenium-server-standalone-3.12.0.jar
INFO: Found latest webdriver version: 2.45
INFO: Found correct webdriver locally: /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/selenium/chromedriver-2.45
INFO: Executing 1 specs
[10:08:35] I/launcher - Running 1 instances of WebDriver
[10:08:38] E/launcher - Cannot define class using reflection
[10:08:38] E/launcher - WebDriverError: Cannot define class using reflection
    at Object.checkLegacyResponse (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:441:30)
    at ManagedPromise.invokeCallback_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:668:7
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at DirectDriverProvider.getNewDriver (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/src/connection/directConnectionProvider.js:480:46)
    at Runner.createBrowser (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:834:54)
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:604:44
    at runSingle (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:125:13)
[10:08:38] E/launcher - Process exited with error code 199
~~~

enviornment:
- macOS 10.14.2
- openjdk version "11.0.2" 2019-01-15
- OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
- OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
- node 11.8.0

**Comment by maximnaidenov** [comment]
Hi Volker,

this is a limitation of the selenium-standalone.jar that we are using. So till they make selenium 3.0 JRE11 compatible, we don't have anything to do. 
A workaround is to set useSeleniumJar: false in the configuration, this will disable the use of selenium jar and directly launch browser drivers. Actually we will make this default soon.

**Comment by vobu** [comment]
wow, thx for the quick response!
can confirm: setting `useSeleniumJar: false` works!
👍
