### ISSUE TITLE
unknown error: session deleted because of page crash

### ISSUE THREAD

**Issue by LukasHeimann** [SAP/ui5-uiveri5#165]
Hi experts,
I'm trying to run UIVeri5 Tests in our Pipeline, but sometimes (and currently more often then not) the tests fail with the following error message:

```
07:58:56 INFO: Opening: https://URL.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home
07:58:56 ERROR: Error while taking report screenshot: NoSuchSessionError: invalid session id
07:58:56 INFO: Expectation FAILED: Failed: unknown error: session deleted because of page crash
07:58:56 from unknown error: cannot determine loading status
07:58:56 from tab crashed
07:58:56   (Session info: chrome=79.0.3945.117)
07:58:56   (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.4.121-92.125-default x86_64)
07:58:56 DEBUG: Expectation FAILED stack: WebDriverError: unknown error: session deleted because of page crash
07:58:56 from unknown error: cannot determine loading status
07:58:56 from tab crashed
07:58:56   (Session info: chrome=79.0.3945.117)
07:58:56   (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.4.121-92.125-default x86_64)
07:58:56     at Object.checkLegacyResponse (/PATH/node_modules/selenium-webdriver/lib/error.js:546:15)
07:58:56     at parseHttpResponse (/PATH/node_modules/selenium-webdriver/lib/http.js:509:13)
07:58:56     at doSend.then.response (/PATH/node_modules/selenium-webdriver/lib/http.js:441:30)
07:58:56     at process._tickCallback (internal/process/next_tick.js:68:7)
07:58:56 From: Task: WebDriver.navigate().to(https://URL.cfapps.sap.hana.ondemand.com/cp.portal/site#Shell-home)
07:58:56     at Driver.schedule (/PATH/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
07:58:56     at Navigation.to (/PATH/node_modules/selenium-webdriver/lib/webdriver.js:1133:25)
07:58:56     at Driver.get (/PATH/node_modules/selenium-webdriver/lib/webdriver.js:988:28)
07:58:56     at FormAuthenticator.get (/PATH/node_modules/@ui5/uiveri5/src/authenticator/formAuthenticator.js:43:18)
07:58:56     at Object.to (/PATH/node_modules/@ui5/uiveri5/src/uiveri5.js:488:25)
07:58:56     at UserContext.<anonymous> (/PATH/src/utils/TestHelper.js:9:35)
07:58:56     at /PATH/node_modules/jasminewd2/index.js:112:25
07:58:56     at new ManagedPromise (/PATH/node_modules/selenium-webdriver/lib/promise.js:1077:7)
07:58:56     at ControlFlow.promise (/PATH/node_modules/selenium-webdriver/lib/promise.js:2505:12)
07:58:56     at schedulerExecute (/PATH/node_modules/jasminewd2/index.js:95:18)
07:58:56 From: Task: Run it("should TESTCASE") in control flow
07:58:56     at UserContext.<anonymous> (/PATH/node_modules/jasminewd2/index.js:94:19)
07:58:56     at attempt (/PATH/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
07:58:56     at QueueRunner.run (/PATH/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
07:58:56     at runNext (/PATH/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4257:20)
07:58:56     at /PATH/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4264:13
07:58:56     at /PATH/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4172:9
07:58:56     at /PATH/node_modules/jasminewd2/index.js:64:48
07:58:56     at ControlFlow.emit (/PATH/node_modules/selenium-webdriver/lib/events.js:62:21)
07:58:56     at ControlFlow.shutdown_ (/PATH/node_modules/selenium-webdriver/lib/promise.js:2674:10)
07:58:56     at shutdownTask_.MicroTask (/PATH/node_modules/selenium-webdriver/lib/promise.js:2599:53)
```

A previous test suite runs green without any failing tests. Downloading and starting the Webdriver seems fine:

```
07:58:39 DEBUG: Resolved protractor multiCapabilities from runtime: [{"browserName":"chrome","platform":"LINUX","chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true},"node_screen_recording":true,"runtime":{"browserName":"chrome","platformName":"linux","platformResolution":"1600x1200","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true},"node_screen_recording":true}}}]
07:58:39 DEBUG: Loading BDD-style page object factory
07:58:39 DEBUG: Setting up connection provider environment
07:58:39 (node:943) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
07:58:40 INFO: Downloading webdriver binary: https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip
07:58:40 INFO: Executing 3 specs
07:58:40 [07:58:40] D/launcher - Running with --troubleshoot
07:58:40 [07:58:40] D/launcher - Protractor version: 5.3.2
07:58:40 [07:58:40] D/launcher - Your base url for tests is undefined
07:58:40 [07:58:40] D/plugins - Plugin "Plugin #0" loaded.
07:58:40 [07:58:40] I/launcher - Running 1 instances of WebDriver
07:58:40 DEBUG: Starting local chromedriver with executable: /PATH/node_modules/@ui5/uiveri5/selenium/chromedriver-79.0.3945.36
07:58:40 [07:58:40] D/runner - WebDriver session successfully started with capabilities Capabilities {
07:58:40   map_:
07:58:40    Map {
07:58:40      'acceptInsecureCerts' => false,
07:58:40      'acceptSslCerts' => false,
07:58:40      'applicationCacheEnabled' => false,
07:58:40      'browserConnectionEnabled' => false,
07:58:40      'browserName' => 'chrome',
07:58:40      'chrome' => { chromedriverVersion:
07:58:40         '79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614})',
07:58:40        userDataDir: '/tmp/.com.google.Chrome.dsAlAC' },
07:58:40      'cssSelectorsEnabled' => true,
07:58:40      'databaseEnabled' => false,
07:58:40      'goog:chromeOptions' => { debuggerAddress: 'localhost:33096' },
07:58:40      'handlesAlerts' => true,
07:58:40      'hasTouchScreen' => false,
07:58:40      'javascriptEnabled' => true,
07:58:40      'locationContextEnabled' => true,
07:58:40      'mobileEmulationEnabled' => false,
07:58:40      'nativeEvents' => true,
07:58:40      'networkConnectionEnabled' => false,
07:58:40      'pageLoadStrategy' => 'normal',
07:58:40      'platform' => 'Linux',
07:58:40      'proxy' => {},
07:58:40      'rotatable' => false,
07:58:40      'setWindowRect' => true,
07:58:40      'strictFileInteractability' => false,
07:58:40      'takesHeapSnapshot' => true,
07:58:40      'takesScreenshot' => true,
07:58:40      'timeouts' => { implicit: 0, pageLoad: 300000, script: 30000 },
07:58:40      'unexpectedAlertBehaviour' => 'ignore',
07:58:40      'version' => '79.0.3945.117',
07:58:40      'webStorageEnabled' => true } }
```

To prevent the crashes we've already tried to add some flags to the chrome execution as recommended elsewhere, but this was of no success:

```js
    chrome: {
      linux: {
        chromeOptions: {
          args: ['--disable-gpu', '--no-sandbox', '--lang=en-US', '--disable-dev-shm-usage']
        }
      }
    }
```

Do you know what could be going wrong here?

Thank you very much for your help!
Kind regards
Lukas

**Comment by maximnaidenov** [comment]
Hi Lukas,
I have observed such random crashes due to docker memory issues but you already applied the --diable-dev-shm-usage flag and in the cases where we observed this, it really helped.   Can you see the logs that this parameter really reaches the browser - is it presented in the multiCapabilites log statement?
Another thing to try would be chrome 80 and respective webdriver. I will push the config to download chromedriver 80 today so maybe you can update the chrome in the container after that and try again ?

**Comment by LukasHeimann** [comment]
Hi Maxim, thank you for your response!

It is in fact overridden somewhere, I wasn't expecting that:

```
07:58:39 DEBUG: Resolved protractor multiCapabilities from runtime: [{"browserName":"chrome","platform":"LINUX","chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true},"node_screen_recording":true,"runtime":{"browserName":"chrome","platformName":"linux","platformResolution":"1600x1200","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars"]},"remoteWebDriverOptions":{"maximized":true},"node_screen_recording":true}}}]
```

Have we maybe misconfigured UIVeri5? This is our full browsers section:

```
  browsers: [
    {
      browserName: environment.browserName,   //'chrome',
      platformName: environment.platformName  //'linux',
    }
  ],

  browserCapabilities: {

    /* maximize browser on all desktops to ensure consistent browser size */
    'firefox,ie,edge,safari,chrome,chromium': {
      'windows,mac,linux': {
        '*': {
          node_screen_recording: true,
          name: environment.seleniumTestName,
          remoteWebDriverOptions: {
            maximized: true
          }
        }
      }
    },
    chrome: {
      linux: {
        chromeOptions: {
          args: ['--disable-gpu', '--no-sandbox', '--lang=en-US', '--disable-dev-shm-usage']
        }
      }
    }
  },
```

In another Pipeline, we use Selenium Grid for Multi-Browser Testing, but in this particular pipeline, we always run chrome on linux.

**Comment by LukasHeimann** [comment]
As discussed with Maxim, the issue was a misconfiguration in browserCapabilities causing the chromeOptions to be not picked up. He recommended not to use the `browserCapabilities`, but rather the documented approach: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/drivers.md

Thank you very much for your help!
