### ISSUE TITLE
GET params in config.baseUrl

### ISSUE THREAD

**Issue by vobu** [SAP/ui5-uiveri5#17]
Hi, me again, sorry :(
It seems that providing GET parameters in `config.baseUrl` only works on launching the first spec, not on subsequent ones.
conf.js:
~~~js
exports.config = {
        //...
	baseUrl: 'http://localhost:9099/index.html?sap-ui-mockserver=true',
        // baseUrl: 'http://localhost:9099/index.html' <- works fine!
	//...
}
~~~

generic.spec.js:
~~~js
describe('generic', () => {
	it('should load the app', () => {
		expect(browser.getTitle()).toBe('title');
	});
});
~~~

zgeneric.spec.js:
~~~js
describe('zgeneric', () => {
	it('should load the app again', () => {
		expect(browser.getTitle()).toBe('title');
	});
});
~~~

Initial launch works, suite + test in generic.spec.js works and executes fine.
In Chrome, the second spec fails to load with a generic "ERR_FAILED", showing `INFO: Expectation FAILED: Failed: Waiting for redirection to complete, target url: http://localhost:9099/index.html?sap-ui-mockserver=true` on the cmd line.
in Firefox, the cmd line shows `INFO: Expectation FAILED: Failed: Reached error page: about:neterror?e=corruptedContentErrorv2`

env:
- @ui5/uiveri5 v1.35.5
- UI5 Version: 1.60.1
- macOS 10.14.2
- openjdk version "11.0.2" 2019-01-15
- OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
- OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
- node 11.8.0

**Comment by vobu** [comment]
Hi Maxim, please find the log attached. Additional info: the local webserver powering localhost:9099 is a plain old grunt connect task.
Extracted relevant (I hope) part:
~~~
[16:45:40] D/launcher - Your base url for tests is http://localhost:9099/index.html?sap-ui-mockserver=true
[16:45:40] I/launcher - Running 1 instances of WebDriver
DEBUG: Starting local chromedriver with executable: /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/selenium/chromedriver-2.46
[16:45:42] D/runner - WebDriver session successfully started with capabilities Capabilities {
  map_:
   Map {
     'acceptInsecureCerts' => false,
     'acceptSslCerts' => false,
     'applicationCacheEnabled' => false,
     'browserConnectionEnabled' => false,
     'browserName' => 'chrome',
     'chrome' => { chromedriverVersion: '2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e)',
       userDataDir:
        '/var/folders/hs/m3xg7_tn08n99scpw758k_8c0000gn/T/.org.chromium.Chromium.F38tKm' },
     'cssSelectorsEnabled' => true,
     'databaseEnabled' => false,
     'goog:chromeOptions' => { debuggerAddress: 'localhost:49939' },
     'handlesAlerts' => true,
     'hasTouchScreen' => false,
     'javascriptEnabled' => true,
     'locationContextEnabled' => true,
     'mobileEmulationEnabled' => false,
     'nativeEvents' => true,
     'networkConnectionEnabled' => false,
     'pageLoadStrategy' => 'normal',
     'platform' => 'Mac OS X',
     'proxy' => {},
     'rotatable' => false,
     'setWindowRect' => true,
     'strictFileInteractability' => false,
     'takesHeapSnapshot' => true,
     'takesScreenshot' => true,
     'timeouts' => { implicit: 0, pageLoad: 300000, script: 30000 },
     'unexpectedAlertBehaviour' => 'ignore',
     'version' => '71.0.3578.98',
     'webStorageEnabled' => true } }
[16:45:42] D/runner - Running with spec files /Users/vbuzek/git/pwa/src/specs/zgeneric.spec.js,/Users/vbuzek/git/pwa/src/specs/zgeneric1.spec.js
DEBUG: Loading module: ./defaultLocators with instance config: {}
DEBUG: Registering default locators
DEBUG: Loading module: ./reporter/consoleReporter with instance config: {}
DEBUG: Loading module: ./reporter/screenshotReporter with instance config: {}
INFO: Suite started: zgeneric
INFO: Spec started: should load the app
DEBUG: Runtime resolved from capabilities: {"browserName":"chrome","platformName":"mac","platformResolution":"1280x1024","browserVersion":"*","platformVersion":"*","deviceName":"*","ui5":{"theme":"belize","direction":"ltr","mode":"cozy"},"capabilities":{"chromeOptions":{"args":["disable-infobars","start-maximized"]}}}
DEBUG: Loading module: ./authenticator/plainAuthenticator with instance config: {}
INFO: Opening: http://localhost:9099/index.html?sap-ui-mockserver=true
DEBUG: Waiting for redirect to complete, current url: http://localhost:9099/index.html?sap-ui-mockserver=true
DEBUG: Initial page load wait: 3000ms
DEBUG: loadUI5Dependencies: Loading waitForUI5 implementation, params: useClassicalWaitForUI5: false ,waitForUI5Timeout: 10800ms ,waitForUI5PollingInterval: 400ms
Loading OPA5 control locator utilities.
Loading OPA5 waitForUI5 implementation.
INFO: UI5 Version: 1.60.1
INFO: UI5 Timestamp: 201811141608
DEBUG: Screenshot created "target/report/screenshots/zgeneric-should-load-the-app_0_pass_2019-02-05T15-45-48.png"
INFO: Spec finished: should load the app with status: PASSED
INFO: Suite finished: zgeneric with status: PASSED for: 6.088s
INFO: Suite specs summary, total: 1, passed: 1, failed: 0, pending: 0, disabled: 0

// here the second test starts
DEBUG: Loading module: ./authenticator/plainAuthenticator with instance config: {}
INFO: Opening: http://localhost:9099/index.html?sap-ui-mockserver=true
DEBUG: Waiting for redirect to complete, current url: chrome-error://chromewebdata/ //<-- repeated a gazillion times
INFO: Expectation FAILED: Failed: Waiting for redirection to complete, target url: http://localhost:9099/index.html?sap-ui-mockserver=true
Wait timed out after 9900ms
DEBUG: Expectation FAILED stack: TimeoutError: Waiting for redirection to complete, target url: http://localhost:9099/index.html?sap-ui-mockserver=true
Wait timed out after 9900ms
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2201:17
    at ManagedPromise.invokeCallback_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:668:7
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
From: Task: Waiting for redirection to complete, target url: http://localhost:9099/index.html?sap-ui-mockserver=true
    at scheduleWait (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2188:20)
    at ControlFlow.wait (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2517:12)
    at Driver.wait (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
    at Object.waitForRedirect (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/src/uiveri5.js:485:33)
    at PlainAuthenticator.get (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/src/authenticator/plainAuthenticator.js:27:40)
    at Object.to (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/src/uiveri5.js:443:25)
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/src/uiveri5.js:370:43
    at TaskQueue.execute_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2974:25)
From: Task: <anonymous>
    at Object.suiteStarted (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/src/uiveri5.js:330:33)
    at dispatch (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4366:28)
    at ReportDispatcher.suiteStarted (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4337:11)
    at nodeStart (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:947:20)
    at UserContext.fn (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5323:13)
    at attempt (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
    at QueueRunner.run (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
    at runNext (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4257:20)
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4264:13
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4172:9
INFO: Expectation FAILED: Failed: Error while waiting for Protractor to sync with the page: "waitForUI5: no UI5 on this page."
DEBUG: Expectation FAILED stack: Error: Error while waiting for Protractor to sync with the page: "waitForUI5: no UI5 on this page."
    at runWaitForAngularScript.then (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/protractor/built/browser.js:463:23)
    at ManagedPromise.invokeCallback_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:668:7
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
From: Task: Run it("should load the app") in control flow
    at UserContext.<anonymous> (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasminewd2/index.js:94:19)
    at attempt (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
    at QueueRunner.run (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
    at runNext (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4257:20)
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4264:13
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4172:9
    at /Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasminewd2/index.js:64:48
    at ControlFlow.emit (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/events.js:62:21)
    at ControlFlow.shutdown_ (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2674:10)
    at shutdownTask_.MicroTask (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2599:53)
From asynchronous test: 
Error
    at Suite.describe (/Users/vbuzek/git/pwa/src/specs/zgeneric1.spec.js:2:2)
    at addSpecsToSuite (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1107:25)
    at Env.describe (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1074:7)
    at describe (/Users/vbuzek/.nvm/versions/node/v11.8.0/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4399:18)
    at Object.<anonymous> (/Users/vbuzek/git/pwa/src/specs/zgeneric1.spec.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
INFO: Spec finished: should load the app with status: FAILED
INFO: Suite finished: zgeneric1 with status: FAILED for: 10.926s
INFO: Suite specs summary, total: 1, passed: 0, failed: 1, pending: 0, disabled: 0
INFO: Suite expectations summary, total: 2, passed: 0, failed total: 2, failed with error: 2, failed with image comparison: 0
INFO: Overall status: FAILED for: 17.018s
INFO: Overall suites summary, total: 2, passed: 1, failed: 1
INFO: Overall specs summary, total: 2, passed: 1, failed: 1, pending: 0, disabled: 0
INFO: Overall expectations summary, total: 3, passed: 1, failed total: 2, failed with error: 2, failed with image comparison: 0
[16:45:59] I/launcher - 0 instance(s) of WebDriver still running
[16:45:59] I/launcher - chrome #01 failed 1 test(s)
[16:45:59] I/launcher - overall: 1 failed spec(s)
DEBUG: Tearing down connection provider environment
[16:45:59] E/launcher - Process exited with error code 1
~~~

**Comment by vobu** [comment]
addtl info: when running with `firefox`, this error occurs:
~~~
INFO: Expectation FAILED: Failed: Reached error page: about:neterror?e=corruptedContentErrorv2&u=http%3A//localhost%3A9099/index.html%3Fmockserver%3Dtrue&c=UTF-8&f=regular&d=Beim%20Laden%20der%20Seite%20http%3A//localhost%3A9099/index.html%3Fmockserver%3Dtrue%20wurde%20gegen%20das%20Netzwerkprotokoll%20versto%C3%9Fen.%20Dieser%20Fehler%20kann%20nicht%20behoben%20werden.
DEBUG: Expectation FAILED stack: WebDriverError: Reached error page: about:neterror?e=corruptedContentErrorv2&u=http%3A//localhost%3A9099/index.html%3Fmockserver%3Dtrue&c=UTF-8&f=regular&d=Beim%20Laden%20der%20Seite%20http%3A//localhost%3A9099/index.html%3Fmockserver%3Dtrue%20wurde%20gegen%20das%20Netzwerkprotokoll%20versto%C3%9Fen.%20Dieser%20Fehler%20kann%20nicht%20behoben%20werden.
~~~
which in turn points to a problem with multiple `Location` http headers...
https://www.mozilla.org/en-US/security/advisories/mfsa2011-39/

**Comment by vobu** [comment]
and now I was able to track down the root cause myself (but still fail to understand it 😟 )
In the local grunt webserver setup, we inject a middleware for rewriting UI5 consumption to the local filesystem (`<script id="sap-ui-bootstrap" src="/resources/sap-ui-core.js"` -> rewrites `/resources` to `/some/path/on/local/filesys`).
If I comment the middleware injection out and directly use the CDN for bootstrapping (`<script id="sap-ui-bootstrap" src="https://openui5.hana.ondemand.com/1.60.1/resources/sap-ui-core.js"`), `uiveri5` runs fine with the 2nd test as well.

But I still fail to understand why with the original setup (with the rewrite middleware), `uiveri5` starts fine with the first test suite, but starts failing from the second one on.

**Comment by vobu** [comment]
Hi Maxim,
was finally able to hunt things down - upfront: no problem of/with `uiveri5`!
Root cause was the implementation of the tested UI5 app as PWA - 1st call to `http://localhost:9099` triggered the service worker installation with all the subsequent `fetch` `cache` mumbo jumo.
2nd call to `http://localhost:9099`, the then active service worker took over - and we were missing the the `index.html`-alias `./` as a cached resource; in the regular user interaction, this didn't pose a problem as the browser auto-triggers a discovery for `./` as `index.html`; but in the remote-control case of the browser, the auto-trigger doesn't happen -> `uiveri5` fails.
So PWA-lesson learned, `uiveri5` working fine, closing this.
