### ISSUE TITLE
Recurring failure of UIVeri5 in Jenkins pipeline 

### ISSUE THREAD

**Issue by vaibhavhirani** [SAP/ui5-uiveri5#170]
Hi,

We are facing this issue due inconsistency behaviour of UIVeri5 element "sap.m.Dialog", that during the execution of the test it is not getting found. 
 In the first link ( in the build 251 ) , it got passed but in the others runs it got failed I have given the link of one of the failure. We have faced the same issue earlier so I changed the declaration of the failing element but we can't keep on doing this because we do not know when the tests are going to fail. 
Please look into it since our pipeline is blocked and as well as our development.

**Comment by maximnaidenov** [comment]
Hi vaibhavhirani,
it won't happen like this - you throw a nasty statement like "inconsistent behavior" a bunch of logs and expect ME to debug YOUR test. If you want help, you will need to do your job before that.
1. Execute the scenario manually and confirm it work as expected
2. Make sure your code is fine - sleep() is a not go for support from us !!! ( touching synchronization or messing up with authentication is an absolute no-go)
3. Fix the htmlexport plugin in your pipeline, it shows incorrect html report link !!!
3. Copy what selector you use, copy screenshot of the relevant section of the control tree, sjow the screenshot of the app state, copy the error log.

**Comment by vaibhavhirani** [comment]
Hi @maximnaidenov ,

Can you let us know regarding the point number 3, which htmlexport plugin are you referring and also regarding the issue, the same behaviour is occuring while executing the test locally also 

 if possible, can we a call and explain the scenario ?

**Comment by maximnaidenov** [comment]
This link shows error:
https://c4prm.codepipes.wdf.sap.corp/job/c4p-rm/job/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/256/console

but this link for the html report shows success:
https://c4prm.codepipes.wdf.sap.corp/job/c4p-rm/job/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/256/HTML_20Reports/

So have a look and fix it. No meaning make any call without going over the above points IN ADVANCE .

**Comment by vaibhavhirani** [comment]
Hi @maximnaidenov ,

You can find the logs for the following runs - 
1. Successful run in pipeline 
[success251.txt](https://github.com/SAP/ui5-uiveri5/files/4212643/success251.txt)

2. Failure in pipeline 
[failure256.txt](https://github.com/SAP/ui5-uiveri5/files/4212644/failure256.txt)

3. Latest local run 
[localrun.txt](https://github.com/SAP/ui5-uiveri5/files/4212645/localrun.txt)

**Comment by maximnaidenov** [comment]
Have you passed over point 1 and 2 ?
Please read again poin4 and prepare the requested snippets.

**Comment by vaibhavhirani** [comment]
Hi @maximnaidenov ,

So we are getting error in search of this following element - sap.m.Dialog, which is that the test is not able to find this element 

![DialogBox](https://user-images.githubusercontent.com/36666451/74644246-017def80-519c-11ea-9ca3-72e79f82fbdf.png)

After inspecting the element -
![inspectDialog](https://user-images.githubusercontent.com/36666451/74644425-41dd6d80-519c-11ea-9e57-07264ea3f59d.png)

How I am using the control -

Consumption of the dialog box 
  
![2020-02-17_15-49-51](https://user-images.githubusercontent.com/36666451/74645002-30489580-519d-11ea-9e37-cdde4f45da36.png)

In the Common Page Elements - 

![2020-02-17_15-49-12](https://user-images.githubusercontent.com/36666451/74645012-35a5e000-519d-11ea-8d9c-c12319c56c20.png)

Control Tree HTML Export -

![HTMLExport](https://user-images.githubusercontent.com/36666451/74647359-89b2c380-51a1-11ea-8a84-d0aa12cae4cb.png)

Control Tree -
**Properties**
![controlTreeP1](https://user-images.githubusercontent.com/36666451/74647109-17da7a00-51a1-11ea-9a7f-030613482fa6.png)

**Properties**
![controlTreeP2](https://user-images.githubusercontent.com/36666451/74647112-1a3cd400-51a1-11ea-9ea9-9eaed819c4ea.png)

**Binding Infos**
![controlTreeP3](https://user-images.githubusercontent.com/36666451/74647116-1ad56a80-51a1-11ea-9142-8ad064a0095c.png)

**Comment by maximnaidenov** [comment]
@vaibhavhirani This is a good start, can you now paste the error AND the RELEVANT screeenshot from the html report in the failure case ?

**Comment by vaibhavhirani** [comment]
Hi @maximnaidenov ,

I have attached the zip file. Go to index.html and select the "test-journey-my-project-experience" and now you should be able to see the test suites which have passed and failed

[HTML_20Reports (1).zip](https://github.com/SAP/ui5-uiveri5/files/4213356/HTML_20Reports.1.zip)

**Comment by maximnaidenov** [comment]
hi @vaibhavhirani, the idea is that I lead you how to solve the problem, not that I search in your logs. 
So again - copy the failure message (available in one of the logs above) and THE RELEVANT screenshot ( the name is available in the log, just a line above the error message)

**Comment by vaibhavhirani** [comment]
Hi @maximnaidenov ,

![part1](https://user-images.githubusercontent.com/36666451/74672402-35c0d280-51d3-11ea-8c17-aa6814b3b907.png)

![part2](https://user-images.githubusercontent.com/36666451/74672408-38232c80-51d3-11ea-9721-40ab3ad97636.png)

Log message - 

NoSuchElementError: No element found using locator: by.control({"controlType":"sap.m.Dialog"})
    at elementArrayFinder.getWebElements.then (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/protractor/built/element.js:814:27)
    at ManagedPromise.invokeCallback_ (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/selenium-webdriver/lib/promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/protractor/built/element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as sendKeys] (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/protractor/built/element.js:91:29)
    at ElementFinder.(anonymous function).args [as sendKeys] (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/protractor/built/element.js:831:22)
    at Object.getSearchField (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/src/tests/pages/PriorExperience.js:82:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: Run it("Should create a new skill and check the skills table for the same") in control flow
    at UserContext.<anonymous> (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/jasminewd2/index.js:94:19)
    at attempt (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
    at QueueRunner.run (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
    at runNext (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4257:20)
    at /home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4264:13
    at /home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4172:9
    at /home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/jasminewd2/index.js:64:48
    at ControlFlow.emit (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/selenium-webdriver/lib/events.js:62:21)
    at ControlFlow.shutdown_ (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/selenium-webdriver/lib/promise.js:2674:10)
    at shutdownTask_.MicroTask (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/selenium-webdriver/lib/promise.js:2599:53)
From asynchronous test: 
Error
    at Suite.<anonymous> (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/src/tests/test-journey-my-project-experience.spec.js:263:5)
    at addSpecsToSuite (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1107:25)
    at Env.describe (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1074:7)
    at describe (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4399:18)
    at Object.<anonymous> (/home/jenkins/workspace/c4p-rm/Resource~Management~Domains~-~~Consultant-Profile~Pipeline-Consultant-Profile-End~to~End~Tests-Run~UIVeri5~Tests/Consultant-Profile/tests/end-to-end/src/tests/test-journey-my-project-experience.spec.js:88:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

**Comment by maximnaidenov** [comment]
@vaibhavhirani So now we see the problem - the dialog is not shown and the locator fails. Can you show the same screenshot  from a successful run ? I imagine it will show the dialog. This also fits with the pattern that you see - passes sometimes and sometimes fails. What is strange is that the waitForUI5 does not wait for the dialog to appear. Can you send me a link to the test so I could check for any problems there ?.

**Comment by vaibhavhirani** [comment]
Hi @maximnaidenov ,

You can have a look at the here -
https://github.wdf.sap.corp/Cloud4RM/Consultant-Profile/blob/0dba143ca1f955ffbd8e60cf5c262e8e2004ec2f/tests/end-to-end/src/tests/test-journey-my-project-experience.spec.js#L263

**Comment by maximnaidenov** [comment]
@vaibhavhirani I still can't grasp the flow of the test in the particular section. According to the log the problem happens at test-journey-my-project-experience.spec.js:263 and exactly inside pages/PriorExperience.js:82. But I do not see such call in this particular it() block ? Are you sure you have the exact same state of the test in github that you show me in the logs ?
