### ISSUE TITLE
firefox by.control not working

### ISSUE THREAD

**Issue by jjellema** [SAP/ui5-uiveri5#173]
Hi!

It seems the by.control locator is not working in firefox. 
In Chrome everything works fine.
I tried by.control locator (within shell.overview.view.po.js below) and jquery selection. 

by.control results in error:
INFO: Expectation FAILED: Failed: No element found using locator: by.control({"viewName":"com.alliander.sapui5.schouwenenafsluiten.view.Overview","controlType":"sap.m.Button","properties":{"id":{"regex":{"source":"RefreshButton","flags":""}}}})

Jquery locator (within shell.overview.view.po.js below) however does work in firefox.

Firefox version: 73.0
geckodriver: geckodriver-v0.26.0-win64

shell.overview.view.po.js
`/* eslint-disable */
const BasePage = require('./basePage');

"use strict"

const viewName = "com.alliander.sapui5.schouwenenafsluiten.view.Overview"

class masterView extends BasePage {
	constructor() {
		super()
		this.Footer = {
			refreshButton: element(by.control({viewName: viewName, controlType: 'sap.m.Button', properties: { id: /RefreshButton/ }})),
			refreshButtonJquery: element(by.jq("span[id*='RefreshButton']")),
		}
	}
}
module.exports = new masterView
`

conf.js:
`module.exports.config = {
	connectionConfigs: {
		direct: {
			binaries: {
				chromedriver: {
					localPath: 'c://chromedriver//chromedriver.exe'
				},
				geckodriver: {
					localPath: 'c://geckodriver//geckodriver.exe'
				}
			}
		}
	},
	profile: "integration",
	baseUrl: 'http://localhost:8080/index2.html',
	specs: 'specs/TestApp.spec.js',
}`

TestApp.spec.js:
`/* eslint-disable */
const MasterView = require('../pages/shell.overview.view.po.js');

describe('TestApp', () => {
	it("navto Mockorder", () => {
		MasterView.Footer.refreshButtonJquery.click()
	})
})`

Is there anything I am doing wrong?

**Comment by tsaleksandrova** [comment]
is the button visible on screen? can you show us the relevant part of the screenshot reports for both browsers?

**Comment by jjellema** [comment]
There is a button visible on the screen (in all scenarios).
Got 3 sets of screenshot reports.
Hope this will suffice

**SuccessChromeByControl:**
Execute 'click' on element with ID '__xmlview1--RefreshButton'

**SuccessFirefoxJquery**
Execute 'click' on element with ID '__xmlview1--RefreshButton-inner' 

**FailFirefoxByControl:**
NoSuchElementError: No element found using locator: by.control({"viewName":"com.alliander.sapui5.schouwenenafsluiten.view.Overview","controlType":"sap.m.Button","properties":{"id":{"regex":{"source":"RefreshButton","flags":""}}}})
    at elementArrayFinder.getWebElements.then (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:814:27)
    at ManagedPromise.invokeCallback_ (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)Error
    at ElementArrayFinder.applyAction_ (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.(anonymous function).args [as click] (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:831:22)
    at UserContext.it (C:\DEV_Mobile\sapui5_SENA\webapp\test\uiveri5\specs\TestApp.spec.js:6:35)
    at C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3067:27)
From: Task: Run it("navto Mockorder") in control flow
    at UserContext.<anonymous> (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
    at C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
    at C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
    at C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:64:48
    at ControlFlow.emit (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\events.js:62:21)
    at ControlFlow.shutdown_ (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2674:10)
    at shutdownTask_.MicroTask (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2599:53)
From asynchronous test: 
Error
    at Suite.describe (C:\DEV_Mobile\sapui5_SENA\webapp\test\uiveri5\specs\TestApp.spec.js:5:2)
    at addSpecsToSuite (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\AL15829\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (C:\DEV_Mobile\sapui5_SENA\webapp\test\uiveri5\specs\TestApp.spec.js:4:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Comment by tsaleksandrova** [comment]
can you send us the configuration file or a link to the deployed app so that we can reproduce this?

**Comment by jjellema** [comment]
I've added the conf.js file above already. 
If that's not enough I'll gladly post a link to the app.

**Comment by jjellema** [comment]
@tsaleksandrova is there any update on this issue?
Where you able to reproduce the issue?

**Comment by tsaleksandrova** [comment]
Hi, your baseUrl is http://localhost:8080/index2.html which means that you serve the app locally somehow. do you have it deployed somewhere I can test? or do you have instructions on where to get the app and how to start it?

**Comment by jjellema** [comment]
hi,
The app is indeed runned locally.
However, it is not deployed somewhere, it is a private app of my company. 
Is there any way we can send it private, or some other way?

**Comment by maximnaidenov** [comment]
Can you somehow make a reproducible sample on site like jsbin ?

**Comment by maximnaidenov** [comment]
Closing due to inactivity.
