### ISSUE TITLE
TypeError: Q.Promise.all is not a function in CI environment

### ISSUE THREAD

**Issue by Fabian-K** [SAP/ui5-uiveri5#188]
Hi,

we are facing a strange issue where our uiveri5 tests fail in the CI environment with:
```
TypeError: Q.Promise.all is not a function
    at LocalSpecResolver._resolveSuite (/usr/local/lib/node_modules/@ui5/uiveri5/src/resolver/localSpecResolver.js:90:20)
    at LocalSpecResolver.resolve (/usr/local/lib/node_modules/@ui5/uiveri5/src/resolver/localSpecResolver.js:67:17)
    at Object.run (/usr/local/lib/node_modules/@ui5/uiveri5/src/uiveri5.js:97:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/@ui5/uiveri5/src/cli.js:69:4)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

We are using v1.42.2. Strangely, I´m not able to reproduce this locally. Do you have any idea what might cause this issue?

Thanks,
Fabian

**Comment by maximnaidenov** [comment]
How do you get UIVeri5 in your CI - npm global install or checkout + npm install?. Maybe you use inconsistent artifacts/dependencies cache from previous versions?

**Comment by Fabian-K** [comment]
That's probably the strangest part. It´s using a container as a build environment:
```
FROM node:12-alpine
RUN npm install @ui5/uiveri5@v1.42.2 -g
```

I did a test with the following and that works both locally and in the ci environment.
```
FROM node:lts-alpine
RUN npm install @ui5/uiveri5@v1.41.0 -g
```

**Comment by zz2014** [comment]
We have the same issue. And this also happens only in ci pipelines

**Comment by maximnaidenov** [comment]
Can you please provide the exact node version on your local environment as well on your CI environment ?

**Comment by zz2014** [comment]
> Can you please provide the exact node version on your local environment as well on your CI environment ?

I am running the tests in a docker container, do my local environment and ci environment still have affects on the version of node?

**Comment by maximnaidenov** [comment]
In docker ot locally, at the end the test is executed by a nodejs. And as you say there is a difference "also happens only in ci pipelines." so I need to know the version on the both places ?

**Comment by zz2014** [comment]
> In docker ot locally, at the end the test is executed by a nodejs. And as you say there is a difference "also happens only in ci pipelines." so I need to know the version on the both places ?

Local version:
```
d063250@C02C184PMD6T git % npm --version
6.13.7
d063250@C02C184PMD6T git % node --version
v13.8.0
```
CI system version:
```
+ npm --version
6.9.0
+ node --version
v10.16.3
```

**Comment by maximnaidenov** [comment]
Hi,
 can you please update the note version in your CI environment to match the local one and try reproducing the problem ?

**Comment by maximnaidenov** [comment]
Closing due to inactivity.
