### ISSUE TITLE
Wrong spec name resolved by localSpecResolver

### ISSUE THREAD

**Issue by h0l0tn1k** [SAP/ui5-uiveri5#202]
Hi,
for some of our jobs uiveri5 tests fail because wrong spec name is resolved from current working directory using `localSpecResolver`.

Our directory e.g.:
```
/var/jenkins_home/ORG/PROJECTNAME/release-1.6/workspace@2/tests/ui/nameOfSpec.spec.js
```

si resolved as:
```
13:03:05  DEBUG: Spec found, name: release-1 , path: /var/jenkins_home/ORG/PROJECTNAME/release-1.6/workspace@2/tests/ui/risk_assessment.spec.js , url: ...
```

but should be: `nameOfSpec`

regex applied is: `(?:\w\:)?\/(?:[\w\-\.]+\/)*([\w\-]+)\.(?:[\w\.]+)`

Thanks,
Stefan.

**Comment by maximnaidenov** [comment]
Can please provide some more details - uiveri5 version, the conf.js content, cmd arguments, relevant section of the console log with -v for debug logs.

**Comment by h0l0tn1k** [comment]
HI @maximnaidenov,
thanks for quick reply.

Details below:

`@ui5/uiveri5@1.42.3`

cmd:
```
uiveri5 --seleniumAddress=http://selenium:4444/wd/hub -v  --specs=./tests/ui/*.spec.js ./tests/ui/conf.js
```
log:
```
DEBUG: Loading default config from: /var/jenkins_home/ORG/PROJECTNAME/release-1.6/workspace@2/tests/ui/conf.js
DEBUG: Current working directory: /var/jenkins_home/ORG/PROJECTNAME/release-1.6/workspace@2
DEBUG: Loading module: ./resolver/localSpecResolver with instance config: {}
INFO: Resolving specs
DEBUG: Resolving specs from: ["./tests/ui/*.spec.js"]
DEBUG: Spec found, name: release-1 , path: /var/jenkins_home/ORG/PROJECTNAME/release-1.6/workspace@2/tests/ui/risk_assessment.spec.js , url: ...

...
D/runner - Running with spec files /var/jenkins_home/ORG/PROJECTNAME/release-1.6/workspace@2/tests/ui/risk_assessment.spec.js
```

error log:
```
INFO: Expectation FAILED: Failed: Spec with full name: risk_assessment not found
DEBUG: Expectation FAILED stack: Error: Spec with full name: risk_assessment not found
    at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/src/uiveri5.js:369:20
    at TaskQueue.execute_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3084:14)
   at TaskQueue.executeNext_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3067:27)
   at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2927:27
   at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:668:7
   at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

conf.js
```
exports.config = {
  baseUrl: ...,
  profile: 'integration',
  auth: {
    ...
  },
  authConfigs: {
    ...
  },
  browsers: [{
    browserName: 'chrome',
    // platformName: 'linux',
  }],
  browserCapabilities: {
    /* maximize browser on all desktops to ensure consistent browser size */
    'chrome,chromium,firefox,ie,edge,safari': {
      'windows,mac,linux': {
        '*': {
          acceptInsecureCerts: true,
          remoteWebDriverOptions: {
            maximized: true,
            browserSize: {
              width: 1500,
              height: 1200
            }
          }
          /*
          seleniumOptions: {
            args: ['-debug', '-log','C:/work/git/openui5/selenium.log']
          }
          */
        }
      }
    },
    /* disable informabrs on chrome, use headless chrome*/
    'chrome,chromium': {
      '*': {
        '*': {
          chromeOptions: {
            // 'w3c': false,
            'args': [
              '--disable-infobars',
              '--headless',
              '--disable-gpu',
              '--no-sandbox',
              '--no-default-browser-check',
              '--disable-default-apps',
              '--no-first-run',
              '--disable-dev-shm-usage',
              '--window-size=1900,1400'
            ]
          },
          /*
          chromedriverOptions: {
            'enableVerboseLogging': [],
            'loggingTo': ['C:\\work\\git\\openui5\\chromedriver.log']
          }
          */
        }
      }
    },
  },

  reporters: [{
    name: './reporter/screenshotReporter'
  }, {
    name: './reporter/jsonReporter'
  }, {
    name: './reporter/junitReporter',
    reportName: './target/report/report.xml'
  }],
  // specs: 'main.spec.js',
  pageLoading: {
    wait: '20000', // provided by default, remove when https://github.wdf.sap.corp/I035254/visualtestjs/issues/27 is done
    initialReload: true
  },
  timeouts: {
    getStepTimeout: 30000,
    allScriptsTimeout: 30000,
    defaultTimeoutInterval: 90000,
    getPageTimeout: 20000
  }
};
```

**Comment by maximnaidenov** [comment]
I don't get what is wrong here. You have a glob pattern ./tests/ui/*.spec.js in a working directory: /var/jenkins_home/ORG/PROJECTNAME/release-1.6/workspace@2 and the file: /var/jenkins_home/ORG/PROJECTNAME/release-1.6/workspace@2/tests/ui/risk_assessment.spec.js obviously matches. The error could mean that the describe() name is different from the file name (except the spec.js part), this is a current limitation.

**Comment by h0l0tn1k** [comment]
describe is written as:
```
describe('risk_assessment', () => {
  ...
});
```

Problem is that LocalSpecResolver parses [here](https://github.com/SAP/ui5-uiveri5/blob/40c74dc6a1f8e3cbc0a8e4b533357c85b4c4cd85/src/resolver/localSpecResolver.js#L109) specName from spec path with incorrect regex i'd say.
And in my example this results to spec name `release-1` instead of `risk_assessment`.

So in my case for path: `/var/jenkins_home/ORG/PROJECTNAME/release-1.6/workspace@2/tests/ui/risk_assessment.spec.js`
Should return: `risk_assessment`
But it returns: `release-1`

**Comment by maximnaidenov** [comment]
aha, now I got it. Thanks for reporting.
IMHO this is because you run uiveri5 in a root folder that is below the spec.js folder. But of course, we should resolve the correct test name. I will add an item to our BL and we will check the regexp with the upcoming restructuring of spec reading, we want to get rid of this limitation for describe and spec name.
