### ISSUE TITLE
Testing an UI5 app with >1 UiVeri5 Specs addresses in 1 conf.js and SSO

### ISSUE THREAD

**Issue by ThommySte** [SAP/ui5-uiveri5#253]
Hi colleagues,
Im facing an Issue during testing my application on SCP NEO with SSO.
Locally on my computer all works fine (with SSO -  and the Auth is disabled). I set up:
```exports.config = {
    specResolver: e2eBase.e2eConfig.specResolver,
    pageLoading: e2eBase.e2eConfig.pageLoading,
    params: e2eBase.e2eConfig.params,
    baseUrl: e2eBase.e2eConfig.baseUrl,
    auth:  // form based
        'sapcloud-form': {
            user: '${params.user}',
            pass: '${params.pass}'
        },
    takeScreenshot: e2eBase.e2eConfig.takeScreenshot,
    reporters: e2eBase.e2eConfig.reqReporters,
    specs: specs,
}
```
Note:  e2eBase.is the base class hold the configuration for Local / Jenkins local / Saucelabs test setups.

Now on Jenkins with the Piper step https://github.wdf.sap.corp/pages/ContinuousDelivery/piper-doc/steps/uiVeri5ExecuteTests/ and an functional technical user configured. I run into the issue that my first spec runs successfully (with a logon and al Steps PASS) but the new spec of the set of spec, I'm facing the problem that the framework  try to do again a logon.
But this failed, because I'm still logon (I check the screenshot taken by the Piper Step).
The shown error for the 2 spec is:
```TimeoutError: Waiting to redirect to login page
Wait timed out after 10011ms
    at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2201:17
    at ManagedPromise.invokeCallback_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2927:27
    at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:668:7
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
From: Task: Waiting to redirect to login page
    at scheduleWait (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2188:20)
    at ControlFlow.wait (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2517:12)
    at WebDriver.wait (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
    at FormAuthenticator._wait (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/src/authenticator/formAuthenticator.js:119:25)
    at FormAuthenticator.get (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/src/authenticator/formAuthenticator.js:60:8)
    at Object.to (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/src/uiveri5.js:524:25)
    at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/src/uiveri5.js:425:43
    at TaskQueue.execute_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2974:25
From: Task: <anonymous>
    at Object.suiteStarted (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/src/uiveri5.js:391:33)
    at dispatch (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4366:28)
    at ReportDispatcher.suiteStarted (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4337:11)
    at nodeStart (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:947:20)
    at UserContext.fn (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5323:13)
    at attempt (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
    at QueueRunner.run (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
    at runNext (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4257:20)
    at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4264:13
    at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4172:9
```
So the UIVer5 try to logon again and try to wait for the SAP-Form, but the App is still logon.
* I tried to spend the a a Logoff button - And press it in the last step of the first step -> Nothing changed.
1) What can I do to avoid a logon for all following specs after the first one
OR
2) What can I do to enforce a logout with a new sapform Login for the following spec

**Comment by maximnaidenov** [comment]
Hi,
I suspect you have issue in clicking the logout button. My suggestion is to reconfigure the local chrome and disable SSO (for some sites or temporary for all sites) and test locally.
Currently UIveri5 executes authentication for every spec, we are working on reworking this limitation but this will take some more time.
And why remark - why do you need to reconfigure the spec resolver? The default one support suites and so you can implement any grouping strategy you may need?

**Comment by ThommySte** [comment]
Hi, 
I replaced the integration profile to get the `junitReporter` in too. In case of using the profile my separate setting was ignored.
So I transfer the required values from https://github.com/SAP/ui5-uiveri5/blob/master/conf/integration.profile.conf.js into my config manually. For this I don't like baut was the only way to get my required changes of the profile in. Did I do something wrong here?
I will have a lock into my logout - Maybe the selector is not 100% ok.
Thanks

**Comment by maximnaidenov** [comment]
This issue was fixed some (>one) years ago - arrays are merged so if you add the junit reporter in your config, it will be added correctly. Please see our docs for examples: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/reporters.md
You can also enable and disable reports as well all modules with config and command line args.

**Comment by ThommySte** [comment]
Hi Maxim,
The issue with the reports I solved now. There was a small discrepancy - Thanks. 
The problem with the logout is still existing. I'm pretty sure I do a functional logoff in the first spec (I tried locally in debug-mode).
But right after processing the 2' spec I get the issue:
[2020-10-27T10:21:06.244Z] INFO: Suite specs summary, total: 12, passed: 12, failed: 0, pending: 0, disabled: 0
[2020-10-27T10:21:06.244Z] INFO: Suite expectations summary, total: 29, passed: 29, failed total: 0, failed with error: 0, failed with image comparison: 0
[2020-10-27T10:21:06.244Z] INFO: Suite started: XXX-2-text2file2text
[2020-10-27T10:21:06.244Z] INFO: Spec started: Navigate from text 2 file and back translation
[2020-10-27T10:21:06.245Z] INFO: Opening: https://XXX/
[2020-10-27T10:21:18.486Z] INFO: Expectation FAILED: Failed: Waiting to redirect to login page
[2020-10-27T10:21:18.486Z] Wait timed out after 10004ms
[2020-10-27T10:21:18.486Z] INFO: Expectation FAILED: Failed: javascript error: UI5 dependencies are not loaded on this pageError: UI5 dependencies are not loaded on this page
[2020-10-27T10:21:18.486Z]     at findByControl (eval at executeScript (:480:16), <anonymous>:5:13)
[2020-10-27T10:21:18.486Z]     at eval (eval at executeScript (:480:16), <anonymous>:31:6)
[2020-10-27T10:21:18.487Z]     at executeScript (<anonymous>:482:30)
[2020-10-27T10:21:18.487Z]     at <anonymous>:487:24
[2020-10-27T10:21:18.487Z]     at callFunction (<anonymous>:450:22)
[2020-10-27T10:21:18.487Z]     at <anonymous>:464:23
[2020-10-27T10:21:18.487Z]     at <anonymous>:465:3
[2020-10-27T10:21:18.487Z]   (Session info: chrome=86.0.4240.75)
Thanks, Thomas

**Comment by maximnaidenov** [comment]
The error message, together with the wait timeout above means that the authetication did not complete. What is the state you see in the relevant screenshot - do you see the credentials entered, any error message in the login page ?

**Comment by ThommySte** [comment]
Hi Maxim,
tobe on the save side 'm double check the logout. i make also witch SauceLabs a video of the Logout (I need a sleep to see something). But now I'm 100% sure the logout is processed in the right way. But I still have the issues with the second spec as before. I enable now the verbose:
```
22:31:26  INFO: Spec started: Logout
22:31:28  DEBUG: Screenshot created "target/report/screenshots/click___xmlview0--logoutButton_0_2020-10-28T21-31-28.png"
22:31:28  INFO: Spec finished: Logout with status: PASSED
22:31:28  INFO: Suite finished: mt-portal-1-text with status: PASSED for: 89.537s
22:31:28  INFO: Suite specs summary, total: 12, passed: 12, failed: 0, pending: 0, disabled: 0
22:31:28  INFO: Suite expectations summary, total: 29, passed: 29, failed total: 0, failed with error: 0, failed with image comparison: 0
22:31:28  INFO: Suite started: mt-portal-2-text2file2text
22:31:28  INFO: Spec started: Navigate from text 2 file and back translation
22:31:28  DEBUG: Loading module: ./authenticator/formAuthenticator with instance config: {"userFieldSelector":"#j_username","passFieldSelector":"#j_password","logonButtonSelector":"#logOnFormSubmit","user":"****","pass":"****"}
22:31:28  INFO: Opening: https://XXX.int.sap.eu2.hana.ondemand.com/
22:31:41  DEBUG: Screenshot created "target/report/screenshots/mt-portal-2-text2file2text-Navigate-from-text-2-file-and-back-translation_0_fail_2020-10-28T21-31-40.png"
22:31:41  DEBUG: Screenshot created "target/report/screenshots/mt-portal-2-text2file2text-Navigate-from-text-2-file-and-back-translation_1_fail_2020-10-28T21-31-40.png"
22:31:41  INFO: Expectation FAILED: Failed: Waiting to redirect to login page
22:31:41  Wait timed out after 10032ms
22:31:41  DEBUG: Expectation FAILED stack: TimeoutError: Waiting to redirect to login page
```
In the video I see the second logon happens automatically without the the user/password query - and UIVeri5 wait to process the logon screen. And this is not shown here.
Thanks, Thomas

**Comment by maximnaidenov** [comment]
Can you please send me the screenshot report. There we have the screenshots at the exact points in time.

**Comment by srinikitha09** [comment]
Hi, 
I am also facing the same issue with the redirection. When I run the uiveri5 tests locally, it works fine without any further authentication, but via pipeline, it is throwing the same error:

 `Failed: Waiting for redirection to complete, target url: xxx`
The target url is on the neo.

**Comment by ZhanJohnny** [comment]
Hi ,

I still face the same issue , the first spec is executed but the left specs are all failed .with error 
 Expectation FAILED: Failed: Waiting to redirect to login page

is this problem not fixed yet ?

**Comment by maximnaidenov** [comment]
@ZhanJohnny 
Can you please open another issue and describe the setup and what error you get exactly.
