### ISSUE TITLE
SaucelabsReporter: Not possible to run tests locally with SaucelabsReporter in config

### ISSUE THREAD

**Issue by adrianna-u** [SAP/ui5-uiveri5#257]
Hi,

we are using the Saucelabs reporter.

	 reporters: [{
		    name: './reporter/saucelabsReporter'}]
		  ,

For simplicity reason, some projects use one config to run against local or sauceLabs.

However,  the local execution is failing.
It is not possible to run tests locally. Logging in failing with the next stack trace:

```
[12:21:40] E/launcher - javascript error: Unexpected identifier
(Session info: chrome=86.0.4240.111)
(Driver info: chromedriver=86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378}),platform=Windows NT 10.0.18363 x86_64)
[12:21:40] E/launcher - JavascriptError: javascript error: Unexpected identifier
(Session info: chrome=86.0.4240.111)
(Driver info: chromedriver=86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378}),platform=Windows NT 10.0.18363 x86_64)
at Object.checkLegacyResponse (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\node_modules\selenium-webdriver\lib\error.js:546:15)
at parseHttpResponse (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\node_modules\selenium-webdriver\lib\http.js:509:13)
at C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\node_modules\selenium-webdriver\lib\http.js:441:30
at processTicksAndRejections (internal/process/task_queues.js:97:5)
From: Task: WebDriver.executeScript()
at Driver.schedule (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
at Driver.executeScript (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\node_modules\selenium-webdriver\lib\webdriver.js:878:16)
at run (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\node_modules\protractor\built\browser.js:59:33)
at ProtractorBrowser.to. (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\node_modules\protractor\built\browser.js:67:16)
at JasmineSaucelabsReporter. (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\src\reporter\saucelabsReporter.js:43:13)
at Spec.jasmine.Spec.addExpectationResult (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\src\reporter\expectationInterceptor.js:12:5)
at Spec.jasmine.Spec.addExpectationResult (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\src\reporter\expectationInterceptor.js:9:58)
at Spec.onException (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:548:10)
at QueueRunner.onException (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:515:50)
at onException (C:\Users\C5231713\AppData\Roaming\npm\node_modules@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4310:14)
[12:21:40] E/launcher - Process exited with error code 199
```

Could this be adjusted, so it is not failing?

Thanks,
Adrianna

**Comment by maximnaidenov** [comment]
Hi Adriana, 
the conf.js is an ordinary node module that simply exports a config object. So you can code whatever logic you want , for example you can have an if statement to add the sauce reporter only if seleniumAddress is defined. Or you may define some execution environment flag to read from the arguments or environment.

**Comment by adrianna-u** [comment]
Hi Maxim,

yes, we are currently using such a work around.  But I need to share this workaround with so many test developers, and it is not easy problem to debug for all of them. Mostly the test developers own 1 app and use UIVeri5 for the  first time. 

Fact is,  the report fails the whole test, when seleniumAdress is not specified, so would be great, if the report is robust and handles this on its own, or maybe fails with User friendly error. So not every app using this report need to build in the check.


Thanks,
Adrianna

**Comment by maximnaidenov** [comment]
Hi Adriana,
I will check how we can do the sauceLabs reporter more robust for missconficurations.

**Comment by maximnaidenov** [comment]
Hi Adrianna,
we documented the correct approach to use the SauceLabs report in local and in CI/CD setups: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/cloud.md
We also plan to adopt this solution in the UIVeri5 yeoman generator that is our supported solution for scaffolding: https://github.com/SAP/generator-easy-ui5.
