### ISSUE TITLE
Script not waiting for element to appear?

### ISSUE THREAD

**Issue by Patrik1957** [SAP/ui5-uiveri5#268]
Hello,

Lately, my Veri5 script is unreliable. In some cases, it wants to find the element before the proper page is loaded, and fails because of this. [Here](https://github.wdf.sap.corp/epd-plmcore/integrationTests/tree/master/uiveri5) is our repository for the scripts, and here is my latest failed report.
![loadSets-Load_1_fail_2020-12-16T06-57-18](https://user-images.githubusercontent.com/55907727/102316110-a2cd0200-3f75-11eb-915d-831891c9b846.png)
![image](https://user-images.githubusercontent.com/55907727/102316189-c3955780-3f75-11eb-966d-411e637fbd2b.png)
`NoSuchElementError: No element found using locator: by.control({"controlType":"sap.m.Button","properties":{"text":"Load"},"ancestor":{"controlType":"sap.m.VBox","properties":{"height":"100%"},"descendant":{"controlType":"sap.m.Title","properties":{"text":"Nutrients"}}}})
    at C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:814:27
    at ManagedPromise.invokeCallback_ (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2927:27
    at C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:668:7
    at processTicksAndRejections (internal/process/task_queues.js:97:5)Error
    at ElementArrayFinder.applyAction_ (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.<computed> [as click] (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.<computed> [as click] (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:831:22)
    at Object.iClickSync (C:\Users\i513744\Desktop\integrationTests\uiveri5\pages\productdbWorklistPage.js:381:38)
    at UserContext.<anonymous> (C:\Users\i513744\Desktop\integrationTests\uiveri5\loadSets.spec.js:58:37)
    at C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3084:14)
From: Task: Run it("Load") in control flow
    at UserContext.<anonymous> (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
    at C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
    at C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
    at C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:64:48
    at ControlFlow.emit (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\events.js:62:21)
    at ControlFlow.shutdown_ (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2674:10)
    at C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2599:53
From asynchronous test: 
Error
    at Suite.<anonymous> (C:\Users\i513744\Desktop\integrationTests\uiveri5\loadSets.spec.js:55:3)
    at addSpecsToSuite (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\i513744\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (C:\Users\i513744\Desktop\integrationTests\uiveri5\loadSets.spec.js:40:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)`

**Comment by maximnaidenov** [comment]
Hi Patrik,
What version of UI5 do you have in your app ? .We had some issues with our waiting (autoWaiter in OPA) that should have started in 1.7X and we finally fixed in 1.84.

**Comment by Patrik1957** [comment]
Hi Maxim,
Fair, I'm running 1.45.1 which is way outdated apparently, how can I update the veri5 version? I tried with global npm uninstall and install but it installed the same version again.

**Comment by vobu** [comment]
> Hi Patrik,
> What version of UI5 do you have in your app ? .We had some issues with our waiting (autoWaiter in OPA) that should have started in 1.7X and we finally fixed in 1.84.

ahhh, might this be the reason why I infrequently see tests  failing with the error message 
`Error: waitAsync is already running and cannot be called again at this moment`?
that would be with UI5 1.74

**Comment by maximnaidenov** [comment]
@vobu 
I don't think it is related, our problem was causing exactly the problem shown in the screenshot - premature synchronization, especially visible while loading an app when navigating from FLP launchpad. And was caused by some changes related to async loading in UI5 so was presented in releases higher than 1.70 up to 1.84 when we fixed it completely.
The "waitAsync is already running" message does not come from our code, sounds like a mutex for concurrently control?

**Comment by maximnaidenov** [comment]
@Patrik1957 
I mean the version of UI5 inside your application, not UIVeri5 tool version.

**Comment by vobu** [comment]
> @vobu
> I don't think it is related, our problem was causing exactly the problem shown in the screenshot - premature synchronization, especially visible while loading an app when navigating from FLP launchpad. And was caused by some changes related to async loading in UI5 so was presented in releases higher than 1.70 up to 1.84 when we fixed it completely.
> The "waitAsync is already running" message does not come from our code, sounds like a mutex for concurrently control?

errmmm:
```shell
~/Doc/m/openui5-sdk-1-73.2 $> grep -r -i "waitAsync is already running" * 
resources/sap/ui/test/autowaiter/_autoWaiterAsync-dbg.js: notifyCallback({error: "waitAsync is already running and cannot be called again at this moment"});
```
stratigh outta UI5 😆

**Comment by maximnaidenov** [comment]
@vobu 
Obviously I have forgotten this. We never hit such issue in UIVeri5 because we have a control flow that enforces the sequence of commands. Could it be that some statement in your test is missing the 'await' statement so it is effectively called in parallel to another one?

**Comment by Patrik1957** [comment]
Thanks @maximnaidenov, I got it now, makes more sense this way. We were running UI5 1.82, hopefully the issue will be fixed once we update then. I'll reopen the issue if the problem still persists afterwards.
