### ISSUE TITLE
The reporters aren't created automatically. 

### ISSUE THREAD

**Issue by volha-zasimovich** [SAP/ui5-uiveri5#272]
Hi, team, I have a problem with the creation of the reporters which are prescribed in the conf.js file. The files with reports created only if we create the corresponding folder before running tests. Expectation: the reports are generated automatically. 
Bellow you can see how settings look in our conf.js file:
reporters: [
        {
            name: './reporter/junitReporter',
            reportName: 'target/report/JunitReport.xml'
        },
        {
            name: './reporter/screenshotReporter',
            reportName: 'index.html'
        }
    ]
 Please, let me know if you don't have the same issue. And maybe any suggestions for resolving the problem.

**Comment by maximnaidenov** [comment]
Can you provide a reproducible sample or logs that show the problem. Because our tests show that screenshot reporter creates the intermediate folders fine.

**Comment by volha-zasimovich** [comment]
[12:44:01] E/launcher - ENOENT: no such file or directory, open 'target/report/PFME2EJUnit.xml'
[12:44:01] E/launcher - Error: ENOENT: no such file or directory, open 'target/report/PFME2EJUnit.xml'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at Object.saveReport (C:\Users\AppData\Roaming\npm\node_modules\@ui5\uiveri5\src\reporter\reporterUtils.js:9:8)
    at JasmineJUnitReporter.jasmineDone (C:\Users\AppData\Roaming\npm\node_modules\@ui5\uiveri5\src\reporter\junitReporter.js:51:9)
    at dispatch (C:\Users\C5281836\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4366:28)
    at ReportDispatcher.jasmineDone (C:\Users\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4337:11)
    at QueueRunner.onComplete (C:\Users\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:994:18)
    at Immediate.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4231:12)
    at processImmediate (internal/timers.js:461:21)

**Comment by volha-zasimovich** [comment]
I've reproduced the sample, it's ok

**Comment by volha-zasimovich** [comment]
When I remove the reporters' block, reports are created automatically

**Comment by volha-zasimovich** [comment]
I have also such settings
takeScreenshot: {
        onExpectFailure: false,
        onExpectSuccess: false,
        onAction: false
    },

**Comment by volha-zasimovich** [comment]
to be precise the parameter onAction, if it is removed, then everything is fine
