### ISSUE TITLE
UIveri5 doest not work in Linux box

### ISSUE THREAD

**Issue by pvalecha-ui5** [SAP/ui5-uiveri5#276]
HI Team,

Getting following error on executing 'uiveri5' command on linux machine (Whereas it works perfectly fine in windows cmd  shell):

 Unable to resolve git branch, seems on detached head, no default one specified
    at /usr/lib/node_modules/@ui5/uiveri5/src/resolver/localUI5SpecResolver.js:84:20
    at Git.<anonymous> (/usr/lib/node_modules/@ui5/uiveri5/node_modules/simple-git/src/git.js:1090:18)
    at done (/usr/lib/node_modules/@ui5/uiveri5/node_modules/simple-git/src/git.js:1429:21)
    at /usr/lib/node_modules/@ui5/uiveri5/node_modules/simple-git/src/git.js:1454:16
    at process._tickCallback (internal/process/next_tick.js:68:7)

![Config](https://user-images.githubusercontent.com/70692404/104419621-b84a4180-559e-11eb-8c48-593f72f20622.png)

**Comment by maximnaidenov** [comment]
you have some messup in what you execute - the log shows that the conf.js misses the profile: 'integration' clause. Maybe you have a different current working directory ?

PS. We develop uiveri5 on linux/mac so no chance it won't work there.
