### ISSUE TITLE
Issue with Dockerizing (Alpine) +  Uiveri5

### ISSUE THREAD

**Issue by Sushanth-B-R** [SAP/ui5-uiveri5#28]
Hi,

Please could you let us know if we can dockerize Uiveri5 and is it compatible with Alpine?

We have built a docker image for Uiveri5, with Base as Alpine and below softwares are part of the container

- nodejs,
- git

- openssh

- JDK

- Chrome (chromium)

- Selenium jar is added

- UIVERI5

Once the image is build, we are cloning the project from git hub url and inside the project folder we are executing the uiveri5 command, but while executing error is generated, Please find the below logs.

Please could you provide guidance in this regard.

Logs:
/usr/src/app/UiVeri5_First # uiveri5
INFO: @ui5/uiveri5 v1.35.6
INFO: Resolving specs
INFO: Check for latest version of: chromedriver
(node:20) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
INFO: Downloading webdriver binary: https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar
INFO: Found latest webdriver version: 2.46
INFO: Downloading webdriver binary: https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip
INFO: Executing 1 specs
[06:17:01] I/launcher - Running 1 instances of WebDriver
[06:17:23] E/launcher - Timed out waiting for driver server to start.
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'bb1785c5a45a', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.125-linuxkit', java.version: '1.8.0_191'
Driver info: driver.version: unknown
[06:17:23] E/launcher - WebDriverError: Timed out waiting for driver server to start.
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'bb1785c5a45a', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.125-linuxkit', java.version: '1.8.0_191'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:441:30)
    at ManagedPromise.invokeCallback_ (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at DirectDriverProvider.getNewDriver (/usr/lib/node_modules/@ui5/uiveri5/src/connection/directConnectionProvider.js:480:46)
    at Runner.createBrowser (/usr/lib/node_modules/@ui5/uiveri5/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/usr/lib/node_modules/@ui5/uiveri5/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/usr/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:863:30)    at Promise.promise.promiseDispatch (/usr/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:604:44
    at runSingle (/usr/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:125:13)
[06:17:23] E/launcher - Process exited with error code 199

**Comment by maximnaidenov** [comment]
Hi,
the error means that the selenium jar is started but webdriver could not connect to it. This usually happens with multihomed machines e.g. several network adapters. To solve it you can either:
1. set useSeleniumJar: false in conf.js of the project. This will disable he use of selenium jar at all and the webdriver will connect to the browser directly. We will make this setting default shortly in uiveri5.
2. set seleniumLoopback: true. This will make the webdriver try to connect to the loo[pback address, where selenium.jas is actually listening.
BTW: you don;t need to download selenium jar manually, uiveri5 will download it automatically and will use only its downloaded jar.

**Comment by OliverNocon** [comment]
@I501604 in case you use Jenkins as your CI environment you could use a ready-made pipeline step for uiveri5. This step re-uses the official node and selenium Docker images from Docker Hub.
You can find details here: 
https://sap.github.io/jenkins-library/steps/uiVeri5ExecuteTests/

**Comment by I501604** [comment]
Hi,
Is there any specific reason why chrome driver downloaded by UIVeri5 is of 2.46 version but not latest stable (73). In case if we need to override the chromedriver which is downloaded by UIVeri5 how do I go about the same.

Chrome driver repository: https://chromedriver.storage.googleapis.com/index.html

**Comment by maximnaidenov** [comment]
Hi Sushant, it seems we missed to recognize chromedriver changed their release naming. As for overriding, you can go on with links as we discussed.

**Comment by Sushanth-B-R** [comment]
Hi Maxim, 
Is it possible to rename chromedriver which is downloaded by UIVeri5 to be named just as chromedriver instead of the convention chromedriver-version 

The reason why am I asking is that, in my current use case I have a docker image based on chromium, chromedriver. In order to run UIVeri5 tests I will have to override the chromedriver downloaded by UIVeri5 due to compatability issues. So it would be easier for everyone to write a simple copy command which involves only chromedriver rather than following a convention of chromedriver-version.

**Comment by maximnaidenov** [comment]
no, this is not possible currently

**Comment by maximnaidenov** [comment]
I am closing as we now support the usage of locally installed webdriver: https://github.com/SAP/ui5-uiveri5/releases/tag/v1.38.0 and this is covering your usecase.
