### ISSUE TITLE
Verify the first row in a sorted table

### ISSUE THREAD

**Issue by Danf0706** [SAP/ui5-uiveri5#311]
I have issues choosing the first row from a sorted table. inspired by https://github.com/SAP/ui5-uiveri5/issues/211, I understand that the best way to solve this issue is using `by.css()` instead of `by.control()`. Then I rewrote my code as the following:
basically what I want to test in this scenario is that the field in my first row is empty because I want to verify that the new draft is always created at the top of this table.

```
newdraftObjectAddedAtTop:function(){
				var firstAssignedObjectsField=element.all(by.css("tr[id*=transfer::IntegrationRunsObjectPage--fe::table::_SyncedObject::LineItem-innerTableRow]")).first().element(by.control({ 
					controlType: "sap.ui.mdc.Field",
					viewName: "sap.fe.templates.ObjectPage.ObjectPage",
					bindingPath: {
						propertyPath: "ObjectID"
					}
				}));
				expect(firstAssignedObjectsField.asControl().getProperty('value')
				).toBe('')				
			},
```
However, I receive the error like the following:

```
InvalidSelectorError: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=90.0.4430.85)
  (Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Windows NT 10.0.18363 x86_64)
    at Object.checkLegacyResponse (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\http.js:441:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
From: Task: WebDriver.findElements(By(css selector, tr[id*=transfer::IntegrationRunsObjectPage--fe::table::_SyncedObject::LineItem-innerTableRow]))
    at Driver.schedule (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at Driver.findElements (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\webdriver.js:1048:19)
    at C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:159:44
    at ManagedPromise.invokeCallback_ (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2927:27
    at C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:668:7
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
From: Task: Run it("add another draft object for transfer run") in control flow
    at UserContext.<anonymous> (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
    at C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
    at C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
From asynchronous test: 
Error
    at Suite.<anonymous> (C:\Users\Username\git\PCI-Tests\app\transfer\webapp\test\uiveri5\test.spec.js:72:2)
    at addSpecsToSuite (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\Username\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (C:\Users\Username\git\PCI-Tests\app\transfer\webapp\test\uiveri5\test.spec.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)

```
Could you please help me understand what have I missed here?

Thanks!

**Comment by maximnaidenov** [comment]
The error message comes from the browser, can you please experiment with this css selector directly in the devtools console ?

**Comment by Danf0706** [comment]
hi @maximnaidenov  in console, I got the error:

```
Uncaught DOMException: Failed to execute '$$' on 'CommandLineAPI': 'tr[id*=transfer::IntegrationRunsObjectPage--fe::table::_SyncedObject::LineItem-innerTableRow]' is not a valid selector.
    at <anonymous>:1:1
```
but the id seems correct 
![image](https://user-images.githubusercontent.com/77449507/116515350-75517700-a8cc-11eb-9f29-4f0610c87abc.png)

This is a Fiori elements app, could you please share some insights on how can I proceed?

**Comment by maximnaidenov** [comment]
Why $$, use the document.querySelectorAll

**Comment by Danf0706** [comment]
found the issue after debug, the id is missing ''; the correct one is: element.all(by.css("tr[id*='transfer::IntegrationRunsObjectPage--fe::table::_SyncedObject::LineItem-innerTableRow']"
