### ISSUE TITLE
Tests not running when browser is set to 'firefox'

### ISSUE THREAD

**Issue by sirirao88** [SAP/ui5-uiveri5#336]
Hi UIVeri5 Team,

I am currently trying to enable cross browser testing for our tests which runs fine for chrome browser. But the tests fail when the browserName is changed to 'firefox'.

**Below is the error seen on Jenkins:**
![image](https://user-images.githubusercontent.com/51156132/129006377-54511cdd-4247-4d0a-abfa-8ea3471ab75c.png)

**Locally I see a slightly different error:**
INFO: Opening webdriver connection with capabilities: {"browserName":"firefox","platform":"WINDOWS","count":1,"loggingPrefs":{"browser":"SEVERE"}}
DEBUG: Starting local geckodriver with executable: C:\Users\I503100\AppData\Roaming\npm\node_modules\@ui5\uiveri5\selenium\geckodriver-v0.29.1.exe
[11:08:21] **E/launcher - Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line[11:08:21] E/launcher - SessionNotCreatedError: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line**
    at Object.throwDecodedError (C:\Users\I503100\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\error.js:514:15)
    at parseHttpResponse (C:\Users\I503100\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\http.js:519:13)
    at C:\Users\I503100\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()

Here is how I have configured in conf.js file which results in above error:
`browsers: [{
        browserName: "firefox"
}],`

But I am able to run fine with below configuration locally:
`browsers: [{
        browserName: "firefox",
        capabilities: {
            geckodriverOptions: {
                enableVerboseLogging: true
            },
            firefoxOptions: {
                addArguments: "-private",
                setBinary: "C:\\Program Files\\Mozilla Firefox\\firefox.exe"
            }
        }
    }],`

Here is the link to our conf file: https://github.wdf.sap.corp/I503100/S4M_UIVeri5/blob/master/conf/onboardingAdmin.conf.js

Also to run the tests with Microsoft edge, one has to copy the edge driver to the @ui5\uiveri5\selenium folder manually. Is there a way to do the same on Jenkins?

Here is how I run the tests on Jenkins:
`uiVeri5ExecuteTests script: this, runOptions: ["--seleniumAddress=http://localhost:4444/wd/hub", "./test/conf/onboardingAdmin.conf.js", "--params.onboardingUser=${onboardingUser}", "--params.onboardingPassword=${onboardingPassword}"]`

Please let me know if you need more details.
Thanks in advance

**Comment by Saurabh-Silori** [comment]
Hi siri,

I am also facing same issue. Are you running same through VSCode or BAS.

**Comment by sirirao88** [comment]
Hi Saurabh,
I am facing this issue on VSCode as well as on Jenkins. Not sure if we get any help here on this

**Comment by maximnaidenov** [comment]
Hi,
the error actually means that the firefox binary is not found. Seems this happens because the gecko driver expects it in another properties key than it is provided by our version of selenium-webdriver. We will have a look but this could take some time.
As for Jenkins, I do not think this is possible in the Fiori Pipeline, as far as I know, there is no firefox browser installed in the dockers at all.

**Comment by sirirao88** [comment]
Thanks Maxim for the reply. I will wait until the issue is resolved.

Also, we are not using the Fiori-pipeline but our own JaaS instance. The tests had run fine a couple of months ago on Jenkins when I had tried firefox browser but not anymore

**Comment by hmanchev** [comment]
UIVeri5 is deprecated and won’t be developed any further. In this regards support for Firefox is not planned to be implemented.
Tests using UIVeri5 will continue to work (Chrome browser) in the foreseeable future. If you are looking for an alternative, you may consider: [WDIO + WDI5](https://blogs.sap.com/2021/11/29/use-wdio-and-wdi5-for-testing-ui5-apps/)
