### ISSUE TITLE
uiVeri5ExecuteTests not working as expected

### ISSUE THREAD

**Issue by simonegaffurini** [SAP/ui5-uiveri5#344]
Hi, I am running into a strange problem with the uiVeri5ExecuteTests on my pipeline.
The same exact project (ui5 app, specs and config) is working correctly on my windows pc when I run the command "uiveri5", but it's giving me a strange error on my pipeline.

### To me it seems that the promises either have some kind of VERY low timeout or the awaits are just ignored.

My config has null as a baseUrl and in beforeAll function I await for a url to load.

This task obviously takes a few seconds, because the ui5 framework is loading.
So, on my windows pc, when I run the test, it takes about 7 seconds to finish the beforeAll function and get to the actual tests of the specs, however if I look at the pipeline logs this is instant.

I doubt this is possible, in fact, if I look at the screenshot of the tests, the page is blank (maybe the browser is still loading the page at that point?).
This is the output (if I look at the output generated from the uiveri5 command on my windows pc there's my app homepage in the screenshot)
![image](https://user-images.githubusercontent.com/87023474/133468070-07a6c471-4500-4fc9-8d64-85f7c97824fd.png)

I also used a library that pings my fiori app to see if it's actually reachable and as you can see the result is yes, it is in fact reachable and there shouldn't be any problem loading it.

This is what I do in my beforeAll function (it's async)
```
...
console.log(`nav to ${url}`)
var reachable = await isReachable(url);
console.log(`pinging ${url}, is reachable? ${reachable}`);
await browser.get(url);
            
await browser.driver.wait(function(){
    console.log("waiting for page to load ui5")
        return browser.driver.findElements(by.css('.sapUshellShellHead')).then(function (elements) {
            return !!elements.length;
    });
}, browser.getPageTimeout, 'Timed out waiting for page to load');
await browser.loadUI5Dependencies();
```

This is the pipeline log
```
info  uiVeri5ExecuteTests - Fiori app server output: Server started
info  uiVeri5ExecuteTests - URL: http://localhost:8080
info  uiVeri5ExecuteTests - 
info  uiVeri5ExecuteTests - nav to http://localhost:8080/test/flpSandbox.html?sap-client=100#testfiori-tile
info  uiVeri5ExecuteTests - pinging http://localhost:8080/test/flpSandbox.html?sap-client=100#testfiori-tile, is reachable? true
info  uiVeri5ExecuteTests - DEBUG: Loading module: ./authenticator/basicUrlAuthenticator with instance config: {"user":"usr","pass":"pwd"}
info  uiVeri5ExecuteTests - INFO: Opening: http://localhost:8080/test/flpSandbox.html?sap-client=100#testfiori-tile
info  uiVeri5ExecuteTests - INFO: Spec started: mytest
info  uiVeri5ExecuteTests - DEBUG: Screenshot created "target/report/screenshots/ListReport-mytest_0_fail_2021-09-15T15-43-48.png"
info  uiVeri5ExecuteTests - pinging http://localhost:8080/test/flpSandbox.html?sap-client=100#testfiori-tile, is reachable? true
info  uiVeri5ExecuteTests - (node:77) UnhandledPromiseRejectionWarning: JavascriptError: javascript error: UI5 dependencies are not loaded on this pageError: UI5 dependencies are not loaded on this page
info  uiVeri5ExecuteTests -     at findByControl (eval at executeScript (:445:16), <anonymous>:5:13)
info  uiVeri5ExecuteTests -     at eval (eval at executeScript (:445:16), <anonymous>:39:6)
info  uiVeri5ExecuteTests -     at executeScript (<anonymous>:447:30)
info  uiVeri5ExecuteTests -     at <anonymous>:452:24
info  uiVeri5ExecuteTests -     at callFunction (<anonymous>:415:22)
info  uiVeri5ExecuteTests -     at <anonymous>:429:23
info  uiVeri5ExecuteTests -     at <anonymous>:430:3
info  uiVeri5ExecuteTests -   (Session info: headless chrome=93.0.4577.63)
info  uiVeri5ExecuteTests - Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
info  uiVeri5ExecuteTests - System info: host: 'b04c3577b89c', ip: '172.25.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.25-linuxkit', java.version: '1.8.0_292'
info  uiVeri5ExecuteTests - Driver info: driver.version: unknown
info  uiVeri5ExecuteTests -     at Object.checkLegacyResponse (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/error.js:546:15)
info  uiVeri5ExecuteTests -     at parseHttpResponse (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:509:13)
info  uiVeri5ExecuteTests -     at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/http.js:441:30
info  uiVeri5ExecuteTests -     at processTicksAndRejections (internal/process/task_queues.js:95:5)
info  uiVeri5ExecuteTests - From: Task: WebDriver.executeScript()
info  uiVeri5ExecuteTests -     at WebDriver.schedule (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
info  uiVeri5ExecuteTests -     at WebDriver.executeScript (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:878:16)
info  uiVeri5ExecuteTests -     at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/by.js:191:35
info  uiVeri5ExecuteTests -     at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:1068:28
info  uiVeri5ExecuteTests -     at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:907:19
info  uiVeri5ExecuteTests -     at ManagedPromise.invokeCallback_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:1376:14)
info  uiVeri5ExecuteTests -     at TaskQueue.execute_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3084:14)
info  uiVeri5ExecuteTests -     at TaskQueue.executeNext_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3067:27)
info  uiVeri5ExecuteTests -     at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2974:25
info  uiVeri5ExecuteTests -     at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:668:7
info  uiVeri5ExecuteTests - From: Task: WebDriver.call(function)
info  uiVeri5ExecuteTests -     at WebDriver.call (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:901:23)
info  uiVeri5ExecuteTests -     at WebDriver.findElementsInternal_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:1068:17)
info  uiVeri5ExecuteTests -     at WebDriver.findElements (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:1043:19)
info  uiVeri5ExecuteTests -     at _ControlLocator.findElementsOverride (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/src/locators/controlLocator.js:65:17)
info  uiVeri5ExecuteTests -     at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/protractor/built/element.js:156:40
info  uiVeri5ExecuteTests -     at ManagedPromise.invokeCallback_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:1376:14)
info  uiVeri5ExecuteTests -     at TaskQueue.execute_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3084:14)
info  uiVeri5ExecuteTests -     at TaskQueue.executeNext_ (/home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:3067:27)
info  uiVeri5ExecuteTests -     at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:2927:27
info  uiVeri5ExecuteTests -     at /home/node/.npm-global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/promise.js:668:7
info  uiVeri5ExecuteTests - (Use `node --trace-warnings ...` to show where the warning was created)
info  uiVeri5ExecuteTests - (node:77) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
info  uiVeri5ExecuteTests - (node:77) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by maximnaidenov** [comment]
Hi, beforeAll is not async function in the version of jasmine we use e.g. the eventual leaked promise from this handler is not waited for. Additionally, the version of webdriverjs we use is using promise flow and so to implement synchronisation with browser operations, you should do browser.driver.control.flow(somePromise); 
BTW. What you do is best done in a custom authenticator, please see https://github.com/SAP/ui5-uiveri5/blob/master/src/authenticator/formAuthenticator.js for hints how you can implement your own authenticator. Then configure it in the conf.js just line the standard ones.

**Comment by simonegaffurini** [comment]
Hi, I tried creating my own authenticator using the formAuthenticator as a template but I can't get it to work.
The idea is: Run a promise that will return me an url -> Navigate to that url -> run specs. I also need to add basic auth to this url.
My first attempt was using the browser.driver.wait, like it's done in formAuthenticator:
```
MyAuthTest.prototype._wait = function (fnCondition, iTimeout, sTimeoutMessage) {
    return browser.driver.wait(fnCondition, iTimeout, sTimeoutMessage);
};

MyAuthTest.prototype.get = async function (url) {
    if (!this.user || !this.pass) {
        return webdriver.promise.rejected(
            new Error('Basic auth requested but user or pass is not specified'));
    }
    
    myPromise.then((sUrl) => {
        this._urlFromPromise = sUrl;
    });

    this._wait(function () {
        return this._urlFromPromise ? true : false
    }, 60000, 'timed out waiting for url');

    url = this._urlFromPromise;
    // prepare basic auth url
    var urlMatches = url.match(/(\w*:?\/\/)(.+)/);
    if (urlMatches === null) {
        return webdriver.promise.rejected(
            new Error('Could not parse url: ' + url));
    }
    var urlWithAuth = urlMatches[1] + this.user + ':' + this.pass + '@' + urlMatches[2];

    // get the url
    return browser.driver.get(urlWithAuth);
};

module.exports = function (config, instanceConfig, logger) {
    return new MyAuthTest(config, instanceConfig, logger);
};
```
in this attempt, the wait is not working, in debug I can see that the debugger goes straight to the `url = this._urlFromPromise;` line without waiting for the promise.

`browser.driver.control.flow(somePromise)`, like you mentioned, gives me Cannot read property 'flow' of undefined.
Looking at the formAuthenticator I saw `browser.controlFlow().execute(fn)` but it gives me the same behaviour of the wait function.

**Comment by maximnaidenov** [comment]
there is already a basicAuthenticator, maybe it fits your requirements ?

**Comment by simonegaffurini** [comment]
It does fit my requirement of authentication, but I still need a way to run a promise and change the url before adding the username and password to it.
This authenticator I made has part of the basic authenicator in it, with the wait (that doesn't work) of the promise.

**Comment by maximnaidenov** [comment]
Messing up control flow, promises and salting this with async/await makes it really hard to grasp what is actually happening. In the code above _wait() works perfectly fine as it is intended to do - it schedules a promise in the flow.And any other operation like browser.go() that also synchronies with control flow will wait for the wait. But any other, non-flow code that needs to work with results of the wait must be executed in a promise handler. OR you should await for this promise, before consuming the results.
