### ISSUE TITLE
Interaction Type must be explicitly mentioned

### ISSUE THREAD

**Issue by timostark** [SAP/ui5-uiveri5#9]
The following code is giving an exception during the assert. Reason is the Exception thrown by the Press OPA handler, which is not getting caught by the _findElements in resources/sap/ui/test/_ControlFinder-dbg.js. Can be solved by adding "interaction: "root"" to the assertion.
_Might be intended behavior_ - Just a little misleading maybe.

*Exception:*
![image](https://user-images.githubusercontent.com/19237828/51306167-f8709b00-1a3c-11e9-9901-8817d10a7902.png)

*Call:*
![image](https://user-images.githubusercontent.com/19237828/51306036-adef1e80-1a3c-11e9-8a48-ca66ebcb7caa.png)

*Log*
```
INFO: Expectation FAILED: Failed: unknown error: Control Element sap.m.List#container-cart---homeView--productList has no dom representation idSuffix was triggerError: Control Element sap.m.List#container-cart---homeView--productList has no dom representation idSuffix was trigger
    at f.$ (https://openui5nightly.hana.ondemand.com/resources/sap/ui/test/actions/Action.js:6:579)
    at g (https://openui5nightly.hana.ondemand.com/resources/sap/ui/test/_ControlFinder.js:6:838)
    at https://openui5nightly.hana.ondemand.com/resources/sap/ui/test/_ControlFinder.js:6:1141
    at Array.map (<anonymous>)
    at Function.b._findElements (https://openui5nightly.hana.ondemand.com/resources/sap/ui/test/_ControlFinder.js:6:871)
    at findByControl (<anonymous>:396:35)
    at <anonymous>:397:6
    at callFunction (<anonymous>:361:33)
    at <anonymous>:371:23
    at <anonymous>:372:3
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 6.1.7601 SP1 x86_64)

```

*Sample*:
test.spec.js
```
describe('test', function () {
    it('Test 0', function () {
        element(by.control({ id: /homeView--searchField/, interaction: { idSuffix: "I" } })).sendKeys('NOT_EXISTING');
        expect(element.all(by.control({ controlType: "sap.m.List", id: /productList/, aggregationEmpty: { name: "items" } })).count()).toBeGreaterThan(0);
    });
});
```

conf.js
```
exports.config = {
    profile: 'integration',
    baseUrl: 'https://openui5nightly.hana.ondemand.com/test-resources/sap/m/demokit/cart/webapp/index.html'
};
```

Thanks,
Timo

**Comment by timostark** [comment]
Close as that is even explicitly mentioned in the documentation..

" The you need to overide the intercation type and search for a focused element"
