### ISSUE TITLE
Use uiveri5 with Appium?

### ISSUE THREAD

**Issue by leonalliander** [SAP/ui5-uiveri5#94]
I was wondering whether you have looked into the possibility to run uiveri5 tests against a cordova (hybrid) app using Appium? 

We currently build our tests using Robot Framework with Appium, but we experience the familiar issues with unstability, difficulty finding elements etc. It would be great to have a UI5 specific library to test our apps.

Appium is based on the webdriver specification, so it suggests it might be possible make uiveri5 compatible with Appium, but I am not familiar enough with the technology to be sure.

**Comment by maximnaidenov** [comment]
Hi,
Appium should work perfectly fine, we have some internal tests for webapps on android. 
Did you try it out, do you face some issues ?

**Comment by leonalliander** [comment]
Are you talking about using testing a .apk file or a webapp running in the (mobile) browser? I am talking about the first. We use cordova to package a UI5 app inside a .apk file.

I didn't get it to work, but I did get it a bit further. I had to remove the validation lines in the runTimeResolver.js for the 'browserName' property in order for it to be left out. Then I ran uiveri5 using this conf.js:

```
exports.config = {
    profile: 'integration',
    browsers: [{
        browserName: "",
        capabilities: {
            platformName: "Android",
            deviceName: "Android",
            app:"C:\\DEV_ROBOT\\uiveri5\\app-debug.apk",
            platformVersion: "8.0",
            newCommandTimeout: "60",
            remoteWebDriverOptions: {
                platformName: "Android",
                deviceName: "Android",
                app:"C:\\DEV_ROBOT\\uiveri5\\app-debug.apk",
                platformVersion: "8.0"
            }
        }
    }]
  };
```

The app does seem to open for a second or so and then the whole process stops with this error message:

```
PS C:\DEV_ROBOT\uiveri5> uiveri5 --seleniumAddress="http://localhost:4723/wd/hub" --timeouts.defaultTimeoutInterval=50000
INFO: @ui5/uiveri5 v1.39.0
INFO: Resolving specs
INFO: Executing 1 specs
(node:9116) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[09:36:07] I/launcher - Running 1 instances of WebDriver
[09:36:20] E/runner - Unable to start a WebDriver session.
[09:36:22] E/launcher - Error: WebDriverError: Not implemented yet for script.
    at Object.checkLegacyResponse (C:\Users\AL9694\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\AL9694\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\AL9694\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.manage().setTimeouts({script: 11000})
    at WebDriver.schedule (C:\Users\AL9694\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at legacyTimeout (C:\Users\AL9694\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\webdriver.js:1433:17)
    at driver_.schedule.catch (C:\Users\AL9694\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\webdriver.js:1387:25)
    at ManagedPromise.invokeCallback_ (C:\Users\AL9694\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\AL9694\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\AL9694\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\AL9694\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\AL9694\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[09:36:22] E/launcher - Process exited with error code 100
```

Any ideas on how to get this further?

**Comment by maximnaidenov** [comment]
We have executions of webapps on chrome on android. The error seems to mean that setting timeout for scripts is not supported. Maybe you can comment out this code for a while ? Please run with -v for debug log.

**Comment by leonalliander** [comment]
Thanks for the advice. I commented out some code in the selenium-webdriver module and it did indeed start up the app. I have to invest some more time to see if I can build a first simple test, but this is an interesting result in any case. The uiveri5 report also comes with some nice screenshots of the app, so that part seems to be compatible as well.

My main question is whether you are thinking of supporting the use of Appium with uiveri5? I had to apply some hacks, so it might be some effort to get this to work properly. Is that something you would consider or is it not in the scope of this framework?

Thanks.

**Comment by maximnaidenov** [comment]
Hi Leon,
We have some common use-cases covered out-of-the-box with UIVeri5 but I suppose there are a lot more that is possible or useful. That's why we use the open-source model - we provided and maintain the base functionality and if you need more, you have the chance to fork our code and add your stuff. And you can PR it and if the covers some minimal quality criteria and does not contradict with some basic requirement (like dependency on VB or broken screenshot report), we would be happy to merge it and hence support it in future.
Our current plans are to work on code coverage, test recording (recorder in UI5 itself) and yeoman generators. Is there is large demand for something more/else, we could consider the priorities but this should be really justified.
